### PR TITLE
[Feature Request] - 'Sign Up' Form Input Area Improved Styling

### PR DESCRIPTION
**Pull request by iamRabia-N**
## Related Issue

Closes: #718

## Description of Changes
This pull request contains the updated code for the _'Sign Up' Form Input Area Improved Styling_ which includes the styling changes in the input areas of the form.
_Design is consistent on all screens._

## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [x] I have included comments in areas that may be difficult to understand.
- [x] I have made corresponding updates to the project documentation.
- [x] My changes have not introduced any new warnings.

## Screenshots

|           Original           |           Updated           |
| :--------------------------: | :-------------------------: |
| op | op|

### CODE REVIEW

**Comment by iamRabia-N** [comment]
Hi @anmode 
Kindly review this pull request.

**Comment by iamRabia-N** [comment]
> Kafi chota change hojaygea.. could you please change sign in too?

Sure

**Comment by anmode** [comment]
yes! tomorrow is last date to merge!

**Comment by iamRabia-N** [comment]
@anmode 
The commit with id '_**308d3f30d9e810cbd1b612e5a8fcf4772a6030f9**_' contains the active state code.

**Comment by iamRabia-N** [comment]
Status: Completed

**Comment by anmode** [comment]
Screenshot 2023-08-10 at 8 11 36 AM
ahh.. see look at nav

**Comment by iamRabia-N** [comment]
> Screenshot 2023-08-10 at 8 11 36 AM ahh.. see look at nav

Yeah, the color of text will change when it active.

**Comment by iamRabia-N** [comment]
This has created balanced look with more highlighted designing on sign up but also have minor details covered with minimal styling

**Comment by anmode** [comment]
Theek ni lg rha h yrr.. Please revert back this and I'll merge then asap!

**Comment by iamRabia-N** [comment]
@anmode Done with reverting commit. You can merge now.

**Pull request merged**
