### PR TITLE
Single form modal for addInternship and addHackathon page

### PR DESCRIPTION
**Pull request by MAXASSASSINS**
## Description of Changes
- Created a new `FormModal` component.
- Created `AddInternship` and `AddHackathon` which use `FormModal` for inputs.
- Renaming `AddInternship` and fixing the path of `AddInternship`
- Fixed the bug on input type number taking 'e' as value.
- Fixed validation on inputs.

## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [x] I have included comments in areas that may be difficult to understand.
- [x] I have made corresponding updates to the project documentation.
- [x] My changes have not introduced any new warnings.

## Screenshots
screenshot-2023-07-28-22-28-56

screenshot-2023-07-28-22-29-11

### CODE REVIEW

**Comment by anmode** [comment]
Please fix the hover effect on button.. all thing look fine

**Comment by MAXASSASSINS** [comment]
Which one?

**Review by anmode — APPROVED** [review]
cool

**Comment by anmode** [comment]
we are now into mentor dashboard creation... if you wanna create issue for that please go ahead...
you see /dashboard/mentor

**Pull request merged**
