### PR TITLE
Refactoring 3

### PR DESCRIPTION
**Pull request by Isha988**
## Related Issue
Follow up for  #481

## Description of Changes
1. Started Working and improving mentors page
2. Added profile card and section component in it

### CODE REVIEW

**Comment by Isha988** [comment]
@anmode  Have a look at mentors page.
1. Is size of card okay?
Screenshot 2023-07-06 at 11-32-57 GrabTern
2. Please also look at code, let me know if I can improve it.
3. Don't worry about input as I have work on it till now .

**Review by anmode — APPROVED** [review]
Nice, I have already reviewed the component.. Now you have used profile card. Great

**Comment by anmode** [comment]
@Isha988 Yes card size is ok

**Comment by anmode** [comment]
I merge it! Please update your branch

**Comment by Isha988** [comment]
> @Isha988 Yes card size is ok, Can we target the Mentor List page and the Mentor Profile page in this PR?

Ya Sure.

**Comment by anmode** [comment]
> > @Isha988 Yes card size is ok, Can we target the Mentor List page and the Mentor Profile page in this PR?
> 
> Ya Sure.

Cool, actually leave mentor profile page for now.
Only mentorList and footer in this pR.

**Comment by Isha988** [comment]
> > > @Isha988 Yes card size is ok, Can we target the Mentor List page and the Mentor Profile page in this PR?
> > 
> > 
> > Ya Sure.
> 
> Cool, actually leave mentor profile page for now. Only mentorList and footer in this pR.

Ya sure, I was thinking for same.

**Comment by Isha988** [comment]
@anmode Mentor list page is ready from my side, if you want any other change so please let me know.

**Comment by anmode** [comment]
I think it is good to remove that banner too, of previous theme

**Comment by anmode** [comment]
Screenshot 2023-07-09 at 11 52 03 AM
This banner....you can just remove it

**Comment by Isha988** [comment]
@anmode  footer is ready.

**Comment by Isha988** [comment]
> Screenshot 2023-07-09 at 11 52 03 AM This banner....you can just remove it

I tried it, but it was not looking good.
Screenshot 2023-07-10 at 12-14-43 GrabTern
If you are okay with this, then I will commit the changes.

**Comment by anmode** [comment]
Cool, all is good. Please commit and this PR is good to merge then

**Comment by Isha988** [comment]
@amode done👍
Please handle prettier formatting for this time, from next pr I will take care of it.

**Comment by anmode** [comment]
> @amode done👍
> Please handle prettier formatting for this time, from next pr I will take care of it.

Cool, Isha
No worries. Actually the thing is in github action we used latest version.
And in package we are using a version back. I updated version in develop branch but your pR is way back 

Great work, thanks

**Comment by anmode** [comment]
Really liked the way you designed the footer. 
👍

**Review by Riyazul555 — APPROVED** [review]

**Comment by Isha988** [comment]
Next pr for mentor profile page or home page transition?

**Comment by anmode** [comment]
> Next pr for mentor profile page or home page transition?

Mentor Profile

**Comment by Isha988** [comment]
> > Next pr for mentor profile page or home page transition?
> se
> Mentor Profile, till time hero section would be ready.

Great! I hope these refactoring pr are improving code base and its structure.

**Comment by anmode** [comment]
yeah! Really These are some imp PRs.
Thanks to you :)

**Pull request merged**
