### PR TITLE
Added profile image  input in user dashboard

### PR DESCRIPTION
**Pull request by Isha988**
Added profile image input in user dashboard profile tab

### CODE REVIEW

**Comment by Isha988** [comment]
@anmode , Why we are not fetching user details on load of profile tab?

**Comment by Isha988** [comment]
I am not sure but we are having some small issues (logical issue) in auth management,
Like,
1. After user/mentor saved and changed its profile image, it is not updating in navbar and sidenav of dashboard. 
2. We are not updating cookies when user/mentor changed its profile
3. We are not updating user/mentor details local storage after user make changes in profile.

**Comment by anmode** [comment]
> @anmode , Why we are not fetching user details on load of profile tab?

oh if it is not! It should be like that... we should fetch user details on load of profile tab!

**Comment by anmode** [comment]
> I am not sure but we are having some small issues (logical issue) in auth management, Like,
> 
> 1. After user/mentor saved and changed its profile image, it is not updating in navbar and sidenav of dashboard.
> 2. We are not updating cookies when user/mentor changed its profile
> 3. We are not updating user/mentor details local storage after user make changes in profile.

1. Yeah I know this problem, Actually we are fetching it with local storage...so on updating local storage needs to update.. your 3rd point is good. 
2. Cookies not need to be update...as we are not using image in that.

**Comment by Isha988** [comment]
> 2\. Cookies not need to be update...as we are not using image in that.

but we are using name in that

**Comment by anmode** [comment]
> > 2. Cookies not need to be update...as we are not using image in that.
> 
> but we are using name in that

haa pr name change hojaye no worries as think of a case, I have updated my details and cookie m value whi h purani and now mai kisi endpoint ko hit kr rha hu , but cookie se only use krte ha mentor_username in case of mentor and user_id in case on user .   So dikkat ni hogi and cookie toh hamesha create hogi on next login!

**Comment by anmode** [comment]
Please the thing you mention can cary on this pR??
Like as updating local storage is a good!

**Comment by Isha988** [comment]
> Please the thing you mention can cary on in this pR?? Like as updating local storage is a good!

okay

**Comment by Isha988** [comment]
@anmode  done from my side, please have a look at changes and let me know if any improvement is required

**Review by anmode — APPROVED** [review]
All cool!

**Pull request merged**
