### PR TITLE
Use overlay on mentor registration form

### PR DESCRIPTION
**Pull request by Isha988**
## Related Issue
Closes: #316

## Description of Changes
- Added overlay component in Mentors registration form
- Removed duplicate function from MentorFormRegistration.js and PersonalDetails.js files

### CODE REVIEW

**Review by anmode — COMMENTED** [review]
The thing is by this the overlay component will only be used by mentorForm... it will not be reusable.

As this overlay should be in other parts where sign-in through Google requires


2ndly: Overlay also needs to improved: https://user-images.githubusercontent.com/88332977/243345094-33b4441a-1a00-4dc4-9de7-ab2f69a20350.png

here is arrow vector: https://www.freepik.com/free-vector/hand-drawn-arrow-set_15961277.htm#query=arrow&position=0&from_view=keyword&track=sph 
The text in overly and this arrow with popup should be aligned!

**Comment by Isha988** [comment]
Point1: done

**Comment by anmode** [comment]
cool, aslo you always forgot to run `npx prettier --write .` command... :)
Actually it will fix the formatting and here on github this test will also pass

**Comment by anmode** [comment]
One issue i think it is good to complete in this pR:
I checked form payload.. I did not all details as filled.  could you recheck by filling form and payload should come in defined format:
```
const InitialFormState = {
    name: "",
    email: "",
    username: "",
    mobile: "",
    internAt: "",
    currentStatus: "",
    social: {
      linkedin: "",
      twitter: "",
    },
    sessions: [],
    schedules: [],
    description: "",
    mentorImg: {
      name: "",
      image: "",
    },
    // resume: '',
    password: `GrabternMentorPW!${number}!`,
    confirmPassword: `GrabternMentorPW!${number}!`,
    verified: false,
  };
```

**Comment by Isha988** [comment]
> One issue i think it is good to complete in this pR: I checked form payload.. The response did not contains all details as filled. could you recheck by filling form and payload should come in defined format:
> 
> ```
> const InitialFormState = {
>     name: "",
>     email: "",
>     username: "",
>     mobile: "",
>     internAt: "",
>     currentStatus: "",
>     social: {
>       linkedin: "",
>       twitter: "",
>     },
>     sessions: [],
>     schedules: [],
>     description: "",
>     mentorImg: {
>       name: "",
>       image: "",
>     },
>     // resume: '',
>     password: `GrabternMentorPW!${number}!`,
>     confirmPassword: `GrabternMentorPW!${number}!`,
>     verified: false,
>   };
> ```

Done, but what is this insecure randomness?

**Comment by Isha988** [comment]
@amode I have improved the overlay a little and I am unable to improve it more, I can try if you provide me some more sample image (how demo looks on different screen size)

**Comment by anmode** [comment]
Screenshot 2023-06-28 at 9 11 32 AM
Isha but google popup is not showing see!

**Comment by anmode** [comment]
1. For mobile it is ok normally popup comes from donw ( good arrow do not needed)
2. The current arrow vector is not good i provided the vector set you can any good vector as suited

**Comment by anmode** [comment]
look at: https://user-images.githubusercontent.com/88332977/243345094-33b4441a-1a00-4dc4-9de7-ab2f69a20350.png

**Comment by anmode** [comment]
> > One issue i think it is good to complete in this pR: I checked form payload.. The response did not contains all details as filled. could you recheck by filling form and payload should come in defined format:
> > ```
> > const InitialFormState = {
> >     name: "",
> >     email: "",
> >     username: "",
> >     mobile: "",
> >     internAt: "",
> >     currentStatus: "",
> >     social: {
> >       linkedin: "",
> >       twitter: "",
> >     },
> >     sessions: [],
> >     schedules: [],
> >     description: "",
> >     mentorImg: {
> >       name: "",
> >       image: "",
> >     },
> >     // resume: '',
> >     password: `GrabternMentorPW!${number}!`,
> >     confirmPassword: `GrabternMentorPW!${number}!`,
> >     verified: false,
> >   };
> > ```
> 
> Done, but what is this insecure randomness?

update your branch! actually we were generated a default password which is less secure...

**Comment by Isha988** [comment]
> 1. For mobile it is ok normally popup comes from donw ( good arrow do not needed)
> 2. The current arrow vector is not good i provided the vector set you can any good vector as suited

Okay.

**Comment by anmode** [comment]
> > > > One issue i think it is good to complete in this pR: I checked form payload.. The response did not contains all details as filled. could you recheck by filling form and payload should come in defined format:
> > > > ```
> > > > const InitialFormState = {
> > > >     name: "",
> > > >     email: "",
> > > >     username: "",
> > > >     mobile: "",
> > > >     internAt: "",
> > > >     currentStatus: "",
> > > >     social: {
> > > >       linkedin: "",
> > > >       twitter: "",
> > > >     },
> > > >     sessions: [],
> > > >     schedules: [],
> > > >     description: "",
> > > >     mentorImg: {
> > > >       name: "",
> > > >       image: "",
> > > >     },
> > > >     // resume: '',
> > > >     password: `GrabternMentorPW!${number}!`,
> > > >     confirmPassword: `GrabternMentorPW!${number}!`,
> > > >     verified: false,
> > > >   };
> > > > ```
> > > 
> > > 
> > > Done, but what is this insecure randomness?
> > 
> > 
> > update your branch! actually we were generated a default password which is less secure...
> 
> my branch was already updated, so I resolved insecure randomness using `window.crypto.getRandomValues(new Uint32Array(1))[0];`

cool!, thanks

**Pull request merged**
