### PR TITLE
[ADDED]: Button test file

### PR DESCRIPTION
**Pull request by Killer2OP**
## Related Issue

Closes: #572 

## Description of Changes

Currently just added the test file for button component.
- created a Test folder
- Created Jest.config.json
- Created Button.test.js
- updated Package.json

## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [x] I have included comments in areas that may be difficult to understand.
- [x] I have made corresponding updates to the project documentation.
- [x] My changes have not introduced any new warnings.

## Screenshots
image

### CODE REVIEW

**Comment by Killer2OP** [comment]
@anmode Right now i just created the test file for button component.
Please review the PR and suggest if you want any changes.

**Comment by anmode** [comment]
Please functional component testing is imp as of now...
for eg. Registration form, login form as user and as mentor, Mentor registration like this!

**Comment by Killer2OP** [comment]
> Please functional component testing is imp as of now... for eg. Registration form, login form as user and as mentor, Mentor registration like this!

OK :)

**Comment by anmode** [comment]
@Killer2OP any update?

**Comment by Killer2OP** [comment]
> @Killer2OP any update?

Yes , I am working on MentorRegistrationForm.
The test cases are designed just making them work.

**Comment by anmode** [comment]
@Killer2OP As you created Test I'll merge this too...
What i think create a seperate Test Folder in root dir.. and we can have same structure for test as our files are present in root dir...

or with file we can have test file?? 
I think 2nd is one is great

**Comment by Killer2OP** [comment]
> @Killer2OP As you created Test I'll merge this too... What i think create a seperate Test Folder in root dir.. and we can have same structure for test as our files are present in root dir...
> 
> or with file we can have test file?? I think 2nd is one is great

the 2nd one is more appropriate. But having all the tests file in a folder is a good practice.
So what should we do?

**Comment by anmode** [comment]
> > @Killer2OP As you created Test I'll merge this too... What i think create a seperate Test Folder in root dir.. and we can have same structure for test as our files are present in root dir...
> > or with file we can have test file?? I think 2nd is one is great
> 
> the 2nd one is more appropriate. But having all the tests file in a folder is a good practice. So what should we do?

haa i think best whi h actually kbhi file update kri toh sath m test bhi update krdenge, so keep test file with the file.

**Comment by Killer2OP** [comment]
> > > @Killer2OP As you created Test I'll merge this too... What i think create a seperate Test Folder in root dir.. and we can have same structure for test as our files are present in root dir...
> > > or with file we can have test file?? I think 2nd is one is great
> > 
> > 
> > the 2nd one is more appropriate. But having all the tests file in a folder is a good practice. So what should we do?
> 
> haa i think best whi h actually kbhi file update kri toh sath m test bhi update krdenge, so keep test file with the file.

DONE. @anmode

**Comment by anmode** [comment]
Prettier is failing

**Pull request merged**
