### PR TITLE
Session update

### PR DESCRIPTION
**Pull request by anmode**
## Related Issue

Closes: #[issue number]

## Checklist:

- [ ] My code adheres to the established style guidelines of this project.
- [ ] I have conducted a self-review of my code.
- [ ] I have included comments in areas that may be difficult to understand.
- [ ] I have made corresponding updates to the project documentation.
- [ ] My changes have not introduced any new warnings.

## Screenshots

|           Original           |           Updated           |
| :--------------------------: | :-------------------------: |
| Original screenshot | Updated screenshot |

Please provide any necessary screenshots to illustrate the changes made.

### CODE REVIEW

**Comment by Isha988** [comment]
I think we should only send session id in query parameter of edit rather than name, type and other details, and then we can fetch the session complete details from api.

I think it is the standard way of doing this.

**Comment by anmode** [comment]
> I think we should only send session id in query parameter of edit rather than name, type and other details, and then we can fetch the session complete details from api.
> 
> I think it is the standard way of doing this.

I too think same:
But now question: To fetch from db we have to make api call and it's time taking process if you carefully see finding a particular session is tough as we will go to search in array of sessions for particular mentor

**Comment by Isha988** [comment]
> finding a particular session is tough as we will go to search in array of sessions for particular mentor

It will be great if you can try this once. https://www.mongodb.com/basics/embedded-mongodb
If it doesn't work than, we will go with your approach.

**Comment by anmode** [comment]
> > finding a particular session is tough as we will go to search in array of sessions for particular mentor
> 
> It will be great if you can try this once. https://www.mongodb.com/basics/embedded-mongodb
> If it doesn't work than, we will go with your approach.

Yeah, I did same in book session,  It will work...chlo api bna hi lete may be khi aur bhi zarurat pde to take out session details based on Id.

**Pull request merged**
