### PR TITLE
feat: testimonials section

### PR DESCRIPTION
**Pull request by rishuraj1**
## Description of Changes
- add:  a dynamic testimonial section to the  ``/mentor`` page.
- refactored FAQ section for better responsiveness

## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [ ] I have included comments in areas that may be difficult to understand.
- [ ] I have made corresponding updates to the project documentation.
- [x] My changes have not introduced any new warnings.

## Screenshots

image

Please provide any necessary screenshots to illustrate the changes made.

### CODE REVIEW

**Comment by anmode** [comment]
Cool,
Just please improve UX work which mentor FAQs

**Comment by rishuraj1** [comment]
@anmode  could you please specify the improvements to be done. Thank you.

**Comment by anmode** [comment]
> @anmode could you please specify the improvements to be done. Thank you.



> @anmode could you please specify the improvements to be done. Thank you.

Just you can put some faqs.... some question that may be regarding:
1. Payout , so there will option to get payout after one month or after each session. 

Another question may be is there any fee deduction from session price?
so ans is no, mentor will get exact price which they set on sessions;

like this please create FAQ... you can use AI

**Comment by rishuraj1** [comment]
@anmode done.

**Comment by anmode** [comment]
cool!

**Comment by anmode** [comment]
we are now into mentor dashboard creation... if you wanna create issue for that please go ahead...
you see /dashboard/mentor

**Pull request merged**
