### PR TITLE
Fixed the links and updated the UI of Refunds Page

### PR DESCRIPTION
**Pull request by divya-2910**
## Related Issue  #149 #147 

Closes: #[issue number]

## Description of Changes

->Fixed the Links of Internship Buttons
->Improved the UI of the Refunds Page
->Also included the footer in it.

## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [x] I have included comments in areas that may be difficult to understand.
- [x] I have made corresponding updates to the project documentation.
- [x] My changes have not introduced any new warnings.

## Screenshots

|           Original           |           Updated           |
| :--------------------------: | :-------------------------: |
image| 
image

## Note : 
->The codebase for the Tnc Page and Privacy Policy Page is pretty messed up (without documentation) and would take a lot of time to fix. So I haven't done that

### CODE REVIEW

**Review by anmode — APPROVED** [review]
cool!

**Comment by anmode** [comment]
Could you pull latest changes and merge in this pr?

**Comment by anmode** [comment]
hey @divya-2910 ? R u up for it? if any issue you can ping

**Comment by divya-2910** [comment]
@anmode On it. I need some time

**Comment by divya-2910** [comment]
@anmode All changes done, check once and approve the PR

**Comment by AmanJain18** [comment]
@anmode Returns policy page is already fixed in this PR #181

**Comment by anmode** [comment]
yeah! Actually in this pR. I was supposing to target all. privacy policy , refund policy and terms & Conditions.

**Comment by anmode** [comment]
@divya-2910 please fix the conficts...then i can review better

**Comment by divya-2910** [comment]
@anmode I think there are no conflicts now

**Comment by AmanJain18** [comment]
why so many lines of changes ? @divya-2910

**Comment by divya-2910** [comment]
@AmanJain18 I think the TNC page was generated using some online generator.
So the person who wrote it forgot to copy the CSS part. Had to rewrite the design part from scratch using new classes and ids

**Review by anmode — CHANGES_REQUESTED** [review]
Like the changes! But could you please fix the uniformity in the font? as you can see Refund policy page. and also achor in the privacy policy or TNC should points exact to the heading to which they refer.

**Comment by divya-2910** [comment]
@anmode 
I made the font style same across all the three pages.  Also heading font style is the same as the index page heading in all 3 pages.
And I have fixed the anchor links in both pages

**Review by anmode — APPROVED** [review]
great! Thank you for this.

**Pull request merged**
