### PR TITLE
New footer using tailwind css

### PR DESCRIPTION
**Pull request by Vidip-Ghosh**
## Related Issue

Designed a new footer using tailwind css. 

Closes: #301 

## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [ ] I have included comments in areas that may be difficult to understand.
- [x] I have made corresponding updates to the project documentation.
- [x] My changes have not introduced any new warnings.

## Screenshots
Screenshot 2023-06-11 at 12 57 33

Please provide any necessary screenshots to illustrate the changes made.

### CODE REVIEW

**Comment by anmode** [comment]
I have added to my review pipeline.. I will test it locally tomorrow sorry, busy today.
Till time see buidl error is coming. please fix it.

**Comment by anmode** [comment]
@Abhinavcode13 @MohitGupta121. please review

**Comment by Vidip-Ghosh** [comment]
> @Abhinavcode13 @MohitGupta121. please review. and @Vidip-Ghosh ... the pic I attached.. please try to use same color coding and i also tagged the source code... could you please extract that color code. and use that. and also please update me too

Okay alright

**Comment by Abhinavcode13** [comment]
LGTM

**Comment by Abhinavcode13** [comment]
Just the color code @Vidip-Ghosh

**Review by anmode — COMMENTED** [review]
Some changes:
1. Our color code is not there. (I have added in issue des.)
2. Email color should be stretched more horizontally.
3. Width is to be reduced ( copywrite section in footer)

I think footer last component ( copywrite section) : `#e2e8f0`
and for more darker areas we can use: `#cbd5e1`

**Comment by anmode** [comment]
here is logo: 
logo_grey-balck-removebg-preview

svg:
logo_grey-balck-removebg-preview

**Comment by Vidip-Ghosh** [comment]
> #cbd5e1

I tried using text-primary but it didn't showed any effect. Therefore I've used text-indigo-400.

**Comment by anmode** [comment]
Screenshot 2023-06-12 at 11 16 04 AM

Actuall This footer color is perfect. We will use whole this theme....but yess instead of this blue we will have purple one. which i taggged.
Ok then you can follow Tailwind footer section wrt to code given

**Comment by Vidip-Ghosh** [comment]
Screenshot 2023-06-12 at 12 29 24
Footer background is white. 
I used purple color for headings.

**Comment by anmode** [comment]
> Screenshot 2023-06-12 at 12 29 24 Footer background is white. I used purple color for headings.

ok so you forgot to add theme to button..... and on hover too theme color should come... wait see: https://doctor-ruby.vercel.app/  how this footer is behaving to there theme color.

**Comment by anmode** [comment]
> > > Screenshot 2023-06-12 at 12 29 24 Footer background is white. I used purple color for headings.
> > 
> > 
> > ok so you forgot to add theme to button..... and on hover too theme color should come... wait see: https://doctor-ruby.vercel.app/ how this footer is behaving to there theme color.
> 
> So, now I just need to add theme to button. Am I right?

keep heading in black ( darker then other links) and yess button should be in theme.  ( please please see the footer i shared with you)

**Comment by Vidip-Ghosh** [comment]
> > > > Screenshot 2023-06-12 at 12 29 24 Footer background is white. I used purple color for headings.
> > > 
> > > 
> > > ok so you forgot to add theme to button..... and on hover too theme color should come... wait see: https://doctor-ruby.vercel.app/ how this footer is behaving to there theme color.
> > 
> > 
> > So, now I just need to add theme to button. Am I right?
> 
> keep heading in black ( darker then other links) and yess button should be in theme. ( please please see the footer i shared with you)

Okay alright

**Comment by Vidip-Ghosh** [comment]
Screenshot 2023-06-12 at 17 19 45
@MohitGupta121 @anmode I hope it's alright.

**Comment by anmode** [comment]
No! Idk why I'm not able to convey:

Our theme color is purple tyep i gave you the code

2nd: i told before header like as services to students should be in black as showed in footer i provided

**Comment by Vidip-Ghosh** [comment]
Screenshot 2023-06-12 at 17 43 11

**Comment by anmode** [comment]
cool @Vidip-Ghosh, Minor changes In UI
Screenshot 2023-06-12 at 8 43 25 PM
- keep the email box on one side and subscribe on one side.

**Comment by Vidip-Ghosh** [comment]
Screenshot 2023-06-12 at 22 51 37
Done with the changes

**Review by anmode — APPROVED** [review]
Impressive @Vidip-Ghosh. Your developing skills are increasing. Cool.
I will put on hold this pR now. I have to wait for other parts of homepage to get complete and will merge all at last.

Requesting you! feel free to any issue/inactive isssue.  or create new issue for new hompage.
Thank you!!

**Comment by anmode** [comment]
Congrats @Vidip-Ghosh

**Comment by anmode** [comment]
@Vidip-Ghosh you did wrongly see- you did wrongly and changed configuration of tailwing to remove that prefix:"-tw"
this is the correct way:
```
<footer tw="-font-sans bg-white dark:bg-[#cbd5e1]">
      <div tw="-flex justify-center md:justify-center">
        <div tw="-mx-auto w-full max-w-screen-xl">
          <div tw="-grid gap-12 px-7 py-6 lg:py-8 md:grid-cols-4 md:divide-x-2 grid-cols-1 text-center">
            <div tw="-footer-logo text-center">
              <div tw="-flex justify-center">
                <a href="index.html">
                  <Image
                    src="/GrabternLogo.svg"
                    width={140}
                    height={90}
                    alt=""
                    tw="-className: sm: mx-60 md:mx-0"
```


I am reverting your changes but no worries changes are safe in this pR you can create another pR with update i suggest

**Pull request merged**
