### PR TITLE
Working of payment tab

### PR DESCRIPTION
**Pull request by Isha988**
## Changes Made
Created workflow for adding, getting and updating account details in mentor dashboard

### CODE REVIEW

**Review by anmode — APPROVED** [review]
Cool, it look good, I think it is good to merge after backend creation!

**Comment by Isha988** [comment]
> Cool, it look good, I think it is good to merge after backend creation!

Backend is done. I have created a pr today

**Comment by anmode** [comment]
Oh ok!!

**Comment by Isha988** [comment]
@anmode you added level label 😂

**Pull request merged**
