### PR TITLE
chore: add favicon and meta tags

### LINKED ISSUE #259: [FEATURE] Meta data with favicon
### Description

A website, especially an open-source one, should have an appropriate favicon and proper meta data for the benefit of crawlers.

I would like to add a favicon based on the official logo of Grabtern.

### Solution Proposed

_No response_

### Screenshots

_No response_

### Additional Context

_No response_

### Checklist

- [X] I have checked the existing [issues](https://github.com/anmode/grabtern-frontend/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/anmode/grabtern-frontend/blob/develop/CONTRIBUTING.md)
- [X] I would like to be assigned this task.
- [X] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by Anmol-Baranwal**
## Related Issue

Closes #259 

## Description of Changes

- Add the favicon

image

- Removed these meta tags from `_document.page.js` due to standard conventions

```html
<meta name="title" content="GrabTern" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
```

Screenshot 2023-06-07 221702

- Add the following meta tags in `_app.page.js`

```html
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta name="language" content="English" />
<meta name="linkedin:profile" content="https://www.linkedin.com/company/grabtern/" />
<meta property="instagram:username" content="https://www.instagram.com/grabtern.guide/" />
<meta name="twitter:site" content="@grabtern_twitter_username" />
```

## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [x] I have included comments in areas that may be difficult to understand.
- [ ] I have made corresponding updates to the project documentation.
- [x] My changes have not introduced any new warnings.

### CODE REVIEW

**Comment by Anmol-Baranwal** [comment]
@anmode,
Could you please review this pull request :)

I would appreciate it if you could provide any feedback or suggest any changes that need to be made.

**Review by anmode — APPROVED** [review]
Looks Cool! Actually we are dealing with a problem. look if you can find a solution. there is google script in this file documents.
https://github.com/anmode/grabtern-frontend/blob/9f0b439f0478ba23a3ccf99a17a3f2d0155001e9/pages/_document.page.js#L8
 actually, that script should be loaded first. 
we have used auth in are components.
eg:https://github.com/anmode/grabtern-frontend/blob/9f0b439f0478ba23a3ccf99a17a3f2d0155001e9/components/MentorFormRegistration.js#L65

so what happens is that we get error `google` is not defined. This comes when script does not loaded. 

This pR is looks good otherwise

**Comment by Anmol-Baranwal** [comment]
> Looks Cool! Actually we are dealing with a problem. look if you can find a solution. there is google script in this file documents.
> https://github.com/anmode/grabtern-frontend/blob/9f0b439f0478ba23a3ccf99a17a3f2d0155001e9/pages/_document.page.js#L8
>  actually, that script should be loaded first. 
> we have used auth in are components.
> eg:https://github.com/anmode/grabtern-frontend/blob/9f0b439f0478ba23a3ccf99a17a3f2d0155001e9/components/MentorFormRegistration.js#L65
> 
> so what happens is that we get error `google` is not defined. This comes when script does not loaded. 
> 
> This pR is looks good otherwise

I will make a different PR if I can solve this.

**Comment by anmode** [comment]
oh okay @Anmol-Baranwal ..Thanks!

**Comment by Anmol-Baranwal** [comment]
@anmode

I have made contributions to multiple projects following the guidelines. As per the guidelines, it is required to add a level tag based on the contribution. Therefore, kindly add the appropriate label tag.

**Pull request merged**
