### PR TITLE
Fixed : issue #165

### PR DESCRIPTION
**Pull request by parthpathakpp1**
## Related Issue

Closes: #165

## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [ ] I have included comments in areas that may be difficult to understand.
- [ ] I have made corresponding updates to the project documentation.
- [x] My changes have not introduced any new warnings.

## Screenshots

|           Original           |           Updated           |
| :--------------------------: | :-------------------------: |
|
grabternrrefundpolicybefore
 |
grabternreturnpolicychange
|

Please provide any necessary screenshots to illustrate the changes made.

### CODE REVIEW

**Review by anmode — APPROVED** [review]
cool! Hyperlink the email.. and also make the heading dark. fix the formatting by `npx prettier --write .`

**Comment by parthpathakpp1** [comment]
> 
@anmode in npx prettier --write after --write I have to give the file name right ???

**Comment by anmode** [comment]
`npx prettier --write . `   remember i used . so it will cover whole code

**Comment by parthpathakpp1** [comment]
> npx prettier --write

@anmode After running the command . Am I supposed to get this result ?
iamsupposedtogetthisresult

**Comment by parthpathakpp1** [comment]
> `npx prettier --write . ` remember i used . so it will cover whole code

@anmode After running this command should I add all the changes or changes I made ??

**Comment by parthpathakpp1** [comment]
> > `npx prettier --write . ` remember i used . so it will cover whole code
> 
> @anmode After running this command should I add all the changes or changes I made only  ??

**Comment by anmode** [comment]
> > `npx prettier --write . ` remember i used . so it will cover whole code
> 
> @anmode After running this command should I add all the changes or changes I made ??

When you run this command...it will format and fix the lint... you just have to save that change.. git add . git commit and puah it!

**Pull request merged**
