### PR TITLE
Responsive the Mentor & Contact us page for all devices

### PR DESCRIPTION
**Pull request by crocmons**
Change UI also Responsive the Mentor & Contact us page for all devices #161 

[Grabtern responsive mentor page.webm](https://github.com/anmode/grabtern-frontend/assets/106610322/61e20fb3-2d24-445b-a211-7761411b0fb7)

### CODE REVIEW

**Review by anmode — APPROVED** [review]
looks cool! can we have small size card in mobile view?? I mean card look bigger....

**Comment by anmode** [comment]
To fix lint test- run `npx prettier --write .`

**Comment by crocmons** [comment]
> To fix lint test- run `npx prettier --write .`

yeah sure, I updated the code now please check..also the card size is now decrease for small devices..

Screenshot (363)

**Review by anmode — APPROVED** [review]
Great! Need some last improvements..
it is not completely responsive...
1. Screenshot 2023-05-29 at 1 51 23 PM

2. Profile pic is very small at mobile device... Could you optimize card. and width of other text but please make sure it should  be responsive.

If any query feel free to ping thank you!

**Comment by AmanJain18** [comment]
having error for tab size devices

**Comment by crocmons** [comment]
> having error for tab size devices

@AmanJain18  Actually my task #161  is only fix the container width for all devices...not to responsive the card for all devices ...but I do the extra responsiveness for only mobile devices..

**Comment by AmanJain18** [comment]
> 

Okay, can u do optimization more properly check atleat 4 diff screen sizes...
UR level Will be upgraded then to 3

**Comment by AmanJain18** [comment]
> > having error for tab size devices
> 
> @anmode @AmanJain18 Actually my task #161 is only fix the container width for all devices...not to responsive the card for all devices ...but I do the extra responsiveness for only mobile devices.. Screenshot (367)

Okay, can u do optimization more properly check atleat 4 diff screen sizes...
UR level Will be upgraded then to 3

**Comment by crocmons** [comment]
> > > having error for tab size devices
> > 
> > 
> > @anmode @AmanJain18 Actually my task #161 is only fix the container width for all devices...not to responsive the card for all devices ...but I do the extra responsiveness for only mobile devices...
> 
> Okay, can u do optimization more properly check atleat 4 diff screen sizes... UR level Will be upgraded then to 3

ok, let me try then..

**Comment by crocmons** [comment]
@anmode updated please check ...now it's responsive for all devices..

**Comment by crocmons** [comment]
@anmode done, fix the lint test.

**Comment by anmode** [comment]
great! work @crocmons appreciating. Thank you! . I'll fix the test.

**Comment by crocmons** [comment]
> great! work @crocmons appreciating. Thank you! . I'll fix the test.

@anmode Thank you but I fix the lint test...

**Comment by crocmons** [comment]
> Button size (Book session) is too large for tablet and mobile devices and image is too small for mobile type devices...



> Button size (Book session) is too large for tablet and mobile devices and image is too small for mobile type devices...

@AmanJain18 I guess it's not a big issue here ...if you want to fix this for tablet as your own assumption please create a separate issue for this & fix this..

**Comment by AmanJain18** [comment]
ya never mind... Thanks for contribution

**Pull request merged**
