### PR TITLE
Refactoring 4

### PR DESCRIPTION
**Pull request by Isha988**
## Related Issue
follow up for #488 

## Description of Changes

Working on mentor profile page

### CODE REVIEW

**Comment by Isha988** [comment]
Is about section looking okay? How to make share link work any suggestion?

**Comment by Isha988** [comment]
add some dummy session data in database so that I can work on session card

**Comment by Isha988** [comment]
Is it okay if I make changes in ` components/Testimonial.js` file for improving testimonial section. I am asking this because it will change testimonial card on `home page`. 
I am thinking of changing it into the testimonial cards of new theme.

**Comment by anmode** [comment]
> Is it okay if I make changes in ` components/Testimonial.js` file for improving testimonial section. I am asking this because it will change testimonial card on `home page`. I am thinking of changing it into the testimonial cards of new theme.

oh actually those testimonial are differnet, In home page we will show through json file ( containing some best testimonial) and in the mentor Profile those testimonial are different in UI from home page and here data will comes from mentor Table.  for now you can have some dummy data, wait I'll provide the api and you can add in this PR only.

**Comment by anmode** [comment]
> add some dummy session data in database so that I can work on session card

sure, I am just changing in backend side so you can fetch session data too

**Comment by anmode** [comment]
about the use of testimonial cards for the new theme
should we have the same on the home page and mentor profile page?? It would look nice 
ok it would be great! We do not have to do coding for two testimonials

**Comment by anmode** [comment]
Ok so i did here is : https://grabtern-backend-demo.vercel.app/api/mentors/mentorDetail/rahul2002

**Comment by anmode** [comment]
> Is about section looking okay? How to make share link work any suggestion?

Share link just make it copy the profile link.
I think we have a modal which display the link and have a button to copy the link

**Comment by Isha988** [comment]
> Ok so i did here is : https://grabtern-backend-demo.vercel.app/api/mentors/mentorDetail/rahul2002

What is the format for following properties in database:
1. Image: image.jpg or complete cloudinary URL
2. Linked and twitter: username like isha123 or https://www.linkedin.com/in/isha123
3. session price: rs 100 or 100
4. session duration: 1 hour or just 60

**Comment by Isha988** [comment]
Is there any list of types of session, if you have then it is possible to add dynamic icons else default icon will be there in session card.

**Comment by anmode** [comment]
> > Ok so i did here is : https://grabtern-backend-demo.vercel.app/api/mentors/mentorDetail/rahul2002
> 
> What is the format for following properties in database:
> 
> 1. Image: image.jpg or complete cloudinary URL
> 2. Linked and twitter: username like isha123 or https://www.linkedin.com/in/isha123
> 3. session price: rs 100 or 100
> 4. session duration: 1 hour or just 60

1. yes it a cloudinary URL
2. From now we will store only username 
3. only value (int)
4. value( int)

**Comment by anmode** [comment]
> Is there any list of types of session, if you have then it is possible to add dynamic icons else default icon will be there in session card.

yess actually for now only session type is call. so default is ok but keeping this is mind for future- can you apply dynamic nature on `session.type`.?

**Comment by Isha988** [comment]
> > Is there any list of types of session, if you have then it is possible to add dynamic icons else default icon will be there in session card.
> 
> yess actually for now only session type is call. so default is ok but keeping this is mind for future- can you apply dynamic nature on `session.type`.?

I can, just need list of different types of session.

**Comment by anmode** [comment]
> > > Is there any list of types of session, if you have then it is possible to add dynamic icons else default icon will be there in session card.
> > 
> > 
> > yess actually for now only session type is call. so default is ok but keeping this is mind for future- can you apply dynamic nature on `session.type`.?
> 
> I can, just need list of different types of session.

sure, sessionType may be: single Call , group call/webinar , text/message. for now only three. we will add a dropdown with these option in mentor form too.

**Comment by anmode** [comment]
One more thing.. I see testimonial cards on home page is uneven. can you fix the card width? I think it is good to slice in extra info

**Comment by Isha988** [comment]
> One more thing.. I see testimonial cards on home page is uneven. can you fix the card width? I think it is good to slice in extra info. actually same card mentor profile page pr bhi h so that's why yhin theek krna shi rhega

okay, but uneven in width or height? Any screenshot will help to get what you want.

**Comment by anmode** [comment]
> > One more thing.. I see testimonial cards on home page is uneven. can you fix the card width? I think it is good to slice in extra info. actually same card mentor profile page pr bhi h so that's why yhin theek krna shi rhega
> 
> okay, but uneven in width or height? Any screenshot will help to get what you want.

Height...just see testimonials of homepage...
Scroll left... you'll clearly see the difference

**Review by anmode — APPROVED** [review]
Cool, Merging this for now,
Actually date picker feature needs this change.
You can fix that testimonial when home page last fix needed or When Hompage good to launch.

**Comment by Isha988** [comment]
> Cool, Merging this for now, Actually date picker feature needs this change. You can fix that testimonial when home page last fix needed or When Hompage good to launch.

Okay, Should I start working on home page now.

**Comment by Isha988** [comment]
I have changed this **const url = `${process.env.NEXT_PUBLIC_BACKEND_URL}/api/mentors/mentorDetail/${mentorUsername}`;**
 To  **const url = `${process.env.NEXT_PUBLIC_BACKEND_URL}/api/mentors/mentorDetail/rahul2002`;** in [mentorUsername].page.js file just for testing purpose and I was not aware that will merge it so early, so please care of it.

**Comment by anmode** [comment]
> > Cool, Merging this for now, Actually date picker feature needs this change. You can fix that testimonial when home page last fix needed or When Hompage good to launch.
> 
> Okay, Should I start working on home page now.

yeah! You can take hero section code from new theme. I'll provide some vector for mentor as there is vector related to doctors

**Comment by anmode** [comment]
> I changed this **const url = `${process.env.NEXT_PUBLIC_BACKEND_URL}/api/mentors/mentorDetail/${mentorUsername}`;** To **const url = `${process.env.NEXT_PUBLIC_BACKEND_URL}/api/mentors/mentorDetail/rahul2002`;** in [mentorUsername].page.js file just for testing purpose and I was not aware that it will get merged so early, so please care of this thing.

oh yess!! I see.. no worries. I'll see. Actually I m thinking to revert to have serverside prop not static prop

**Comment by Isha988** [comment]
> > I changed this **const url = `${process.env.NEXT_PUBLIC_BACKEND_URL}/api/mentors/mentorDetail/${mentorUsername}`;** To **const url = `${process.env.NEXT_PUBLIC_BACKEND_URL}/api/mentors/mentorDetail/rahul2002`;** in [mentorUsername].page.js file just for testing purpose and I was not aware that it will get merged so early, so please care of this thing.
> 
> oh yes!! I see. no worries. I'll see. Actually, I m thinking to revert back to have serverside prop, not static prop

I think other than this all are serve side props.
You can, I will also correct the social urls in the about section.

**Comment by anmode** [comment]
Hey, Please update the branch. Recently Hero section is complete.
Now homepage refactoring you can start. 
I think as we are using tailwind,  it is good to  completely removed from our codebase.

**Comment by Isha988** [comment]
> Hey, Please update the branch. Recently Hero section is complete. Now homepage refactoring you can start. I think as we are using tailwind, it is good to completely removed from our codebase.

What to completely removed from codebase?

**Comment by anmode** [comment]
> > Hey, Please update the branch. Recently Hero section is complete. Now homepage refactoring you can start. I think as we are using tailwind, it is good to completely removed from our codebase.
> 
> What to completely removed from codebase?

scss files that are not used... actually what we did in past days. we applied tailwind.. you too but we haven't removed the old styling files.

**Comment by Isha988** [comment]
> > > Hey, Please update the branch. Recently Hero section is complete. Now homepage refactoring you can start. I think as we are using tailwind, it is good to completely removed from our codebase.
> > 
> > 
> > What to completely removed from codebase?
> 
> scss files that are not used... actually what we did in past days. we applied tailwind.. you too but we haven't removed the old styling files.

Okay great, but we have to do it very carefully because maybe there is some code which are using those style.

**Comment by anmode** [comment]
> > > > Hey, Please update the branch. Recently Hero section is complete. Now homepage refactoring you can start. I think as we are using tailwind, it is good to completely removed from our codebase.
> > > 
> > > 
> > > What to completely removed from codebase?
> > 
> > 
> > scss files that are not used... actually what we did in past days. we applied tailwind.. you too but we haven't removed the old styling files.
> 
> Okay great, but we have to do it very carefully because maybe there is some code which are using those style.

yeah you are correct.

**Pull request merged**
