### PR TITLE
Created Internship Page with Search, Filter, and Exploration Functionality

### PR DESCRIPTION
**Pull request by Nishitbaria**
## Related Issue

I have created a new Internship Page with added features of search and filter functionality using chips. This pull request includes the necessary code changes to implement these features.

Closes: #[#457]

## Description of Changes

- Created a new Internship Page component that displays a list of internships.
- Implemented search functionality to search for internships based on keywords.
- Added filter functionality using chips to narrow down internship results based on specific categories or preferences.
- Developed reusable components like Gallery Card to display individual internship cards and Search Bar for the search functionality.

**Details:**
- Designed and implemented the Internship Page layout using reusable components for improved maintainability and extensibility.
- Integrated search functionality using the Search Bar component, allowing users to enter keywords and find internships matching their search queries.
- Implemented filter options using chips within the Gallery Card component, enabling users to select specific categories or preferences to refine their internship results.
- Developed the necessary logic and backend integration to fetch and display the filtered internship results based on the selected search and filter options.

**Technical Changes:**
- Created reusable components like Gallery Card, which accepts props for displaying individual internship information.
- Implemented the Search Bar component to handle search functionality and update the internship list accordingly.
- Updated the Internship Page component to render a list of Gallery Card components, passing the necessary props for each internship.

## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [x] I have included comments in areas that may be difficult to understand.
- [x] I have made corresponding updates to the project documentation.
- [x] My changes have not introduced any new warnings.

## Screenshots

|           Original           |           Updated           |
| :--------------------------: | :-------------------------: |
| Original screenshot | Updated screenshot |

Thank you for considering this pull request. I look forward to your feedback and merging these changes into the main repository.

### CODE REVIEW

**Comment by Nishitbaria** [comment]
@anmode,please preivew and merge my pull request

**Comment by anmode** [comment]
two things which i noticed in preview:
1. Remove sign up button idk why it is coming
2. Please use new nav bar in internship page 
Same changes in your hackathon page

**Comment by anmode** [comment]
after these fix.. I review PR

**Comment by Nishitbaria** [comment]
> after these fix.. I review PR, good work btw appricating. @Nishitbaria I am making a project. I need in frontend part. If you wish to collaborate. Please let me know. we can have meet

hey @anmode  i update your changes :) ✔

**Comment by anmode** [comment]
Cool, Congrats.
You did not respond to my message :)
so you may think what you will get in return:
1. Experience
2. goodies or share from my side. if you up for this lemme know. ( language is Angular and typescript)

**Comment by Nishitbaria** [comment]
> Cool, Congrats.
> You did not respond to my message :)
> so you may think what you will get in return:
> 1. Experience
> 2. goodies or share from my side. if you up for this lemme know. ( language is Angular and typescript)
> 

I don't have any experience in agluer and Typescript if your project in MERN STACK I CAN DO THAT BUT ISME SE MUJE KUCHA BHI NAI AATA HE  :(
 IF YOUR WORK IN REACT OR NEXTJS I CAN DO IT BUT ITS IN AGULER

**Pull request merged**
