### PR TITLE
fix: lacking label for newsletter and incorrect way of displaying heading on login page 👷🏻🛠

### PR DESCRIPTION
**Pull request by 0xabdulkhalid**
## Related Issue

Closes: #605 & #608

## Description of Changes
- First, We added proper label for the newsletter form which can be found on Footer with proper attributes so that the `input` and `label` would associate properly for accessibility devices.
- The `label` is visually hidden, It's only visible for accessibility devices using the `sr-only` tailwind utility class.
- Second, We fixed the incorrect case of Heading on Login page using string methods of JavaScript.
- `entityType` is the variable that holds a string, either "user" or "mentor".
- `.charAt(0)` is the method which gets the first character of the `entityType` string.
- `.toUpperCase()`  converts the first character of `entityType` to uppercase.
- `+  entityType.slice(1)` used for concatening the uppercased letter with `slice` which extracts the part of the `entityType` string starting from the second character (index 1) until the end of the string.

## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [x] I have included comments in areas that may be difficult to understand.
- [x] I have made corresponding updates to the project documentation.
- [x] My changes have not introduced any new warnings.

## Screenshots

https://github.com/anmode/grabtern-frontend/assets/92252895/15129ba3-186b-438c-9dd1-152dbe35a91a

### CODE REVIEW

**Comment by 0xabdulkhalid** [comment]
@anmode your review is appreciated 🙌🏻

**Comment by 0xabdulkhalid** [comment]
By the way @anmode, Can i know is anyone changed the Logo ?

Because in this PR's deployed site there's an alternative logo is present in name of old Logo, You can look the below video to see the difference.

https://github.com/anmode/grabtern-frontend/assets/92252895/2ea5cff2-134c-4004-a45b-db32e5e0cb83

**Comment by anmode** [comment]
yes it was changes by mistake please replace that in this PR only

**Comment by 0xabdulkhalid** [comment]
@anmode can make your statement more concise ?

Do i want to fix that issue in this PR ?

**Comment by anmode** [comment]
> @anmode can make your statement more concise ?
> 
> Do i want to fix that issue in this PR ?

yess please fix that issue in this pR only!

**Comment by 0xabdulkhalid** [comment]
@anmode PR is ready to merge 🚀 🔥

**Pull request merged**
