### PR TITLE
SectionImproved

### PR DESCRIPTION
**Pull request by ShreyaDhiman24**
## Related Issue

Closes: #382 

## Description of Changes

image

## Checklist:

-  [x]My code adheres to the established style guidelines of this project.
-  [x] I have conducted a self-review of my code.
-  [x] I have included comments in areas that may be difficult to understand.
-  [x]I have made corresponding updates to the project documentation.
-  [x] My changes have not introduced any new warnings.

### CODE REVIEW

**Comment by anmode** [comment]
Screenshot 2023-06-21 at 8 19 13 AM
Error!!

**Comment by anmode** [comment]
Ah, @ShreyaDhiman24 I forget there is an ongoing PR for the same section! Could you work on other issues??? as how mentor profile page can me made more interactive. 
A testomonial section is a good idea. and it will be nice contribution too ( new feature)

**Comment by ShreyaDhiman24** [comment]
> Screenshot 2023-06-21 at 8 19 13 AM Error!!

But it's not showing any error here.

**Comment by ShreyaDhiman24** [comment]
> Ah, @ShreyaDhiman24 I forget there is an ongoing PR for the same section! Could you work on other issues??? as how mentor profile page can me made more interactive. A testomonial section is a good idea. and it will be nice contribution too ( new feature)

@anmode But then what about the work I have done ..

**Comment by anmode** [comment]
> > Ah, @ShreyaDhiman24 I forget there is an ongoing PR for the same section! Could you work on other issues??? as how mentor profile page can me made more interactive. A testomonial section is a good idea. and it will be nice contribution too ( new feature)
> 
> @anmode But then what about the work I have done ..

I understand! but changes I personally did not like. Making that bold and colorful distorted the UI and hover effect covering the text area.
And this section will be removed as there is mentor page. if you want you can improve UX of that and changes would be simple for loss here will be covered there.
see in `public` folder `mentor.paga.js`

**Pull request closed without merging**
