### PR TITLE
Fixed isssue #222 added search bar

### PR DESCRIPTION
**Pull request by ePSA-eJya**
## Related Issue

Closes: #[#222]

## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [x] I have included comments in areas that may be difficult to understand.
- [x] I have made corresponding updates to the project documentation.
- [x] My changes have not introduced any new warnings.

## Screenshots

|           Original           |           Updated           |
| :--------------------------: | :-------------------------: |
| 
image
 | 
image
 |

Please provide any necessary screenshots to illustrate the changes made.
image

Search bar can filter on basis of name, interntype and currentstatus.

### CODE REVIEW

**Comment by ePSA-eJya** [comment]
@Abhinavcode13 @anmode please review and merge the pr.
also add a level label.

**Review by anmode — COMMENTED** [review]
Is that possible to use and search at all cases?? 
I mean if `gssoc -. Gssoc`  then too we can get result?
btw good approach.... thanks

**Comment by anmode** [comment]
@Riyazul555

**Review by anmode — APPROVED** [review]

**Review by Riyazul555 — APPROVED** [review]

**Comment by anmode** [comment]
thanks @ePSA-eJya !!

**Pull request merged**
