### PR TITLE
@shivang-16 updated userLoginFormanMentorLoginForm

### PR DESCRIPTION
**Pull request by shivang-16**
Related issue: Remove extra bottom space in Mentors and User Form page #123

I have removed the extra space from user login page and also added media query for user login page and mentor login page and now both are working fine in all type of devices.  

You can review all the changes and if there is any issue then kindly contact me.
Thankyou

### CODE REVIEW

**Comment by anmode** [comment]
Please could you tell what you have changed? through UI. and according to the issue. You should fix the session UI.

**Comment by anmode** [comment]
Screenshot 2023-05-30 at 9 32 09 AM
if you can fix it! and some UI improvment. I will mark this PR as level 2

**Comment by shivang-16** [comment]
Ok I will fix it by tomorrow 🙂

**Comment by anmode** [comment]
@shivang-16 there is UI problem I guess. Can you create new UI card. So this type of problem do not arise and it also looks great.
Screenshot 2023-05-30 at 9 32 09 AM

**Comment by shivang-16** [comment]
> @shivang-16 there is UI problem I guess. Can you create new UI card. So this type of problem do not arise and it also looks great. Screenshot 2023-05-31 at 9 19 04 AM

Ok I'll see it

**Comment by shivang-16** [comment]
now you can see.. its looking fine..i have fixed it
Screenshot 2023-05-31 121830

**Comment by anmode** [comment]
Great! But when you see mobile mode:
Screenshot 2023-05-31 at 1 56 58 PM


if you facing an issue in responsiveness.. you can Suggest a new UI card design. and can use it

**Comment by shivang-16** [comment]
I tried to new UI card design but unable to fix the issue of reponsiveness....
If we change the seesion description of Resume Review and make it little longer as 1 on 1 mentorship  ..then problem will we solved ..but I'm not able to find the session description

**Comment by shivang-16** [comment]
now you can see i have updated the UI
Screenshot 2023-05-31 213717
Screenshot 2023-05-31 213810

**Comment by anmode** [comment]
It's good! But where is the session description? and one more thing please look:

https://github.com/anmode/grabtern-frontend/assets/88332977@muhammadjufry a4f6554-56b6-4ecc-a0eb-07e12459ff4f

@muhammadjufry any suggestions? please

**Comment by shivang-16** [comment]
now i think everthing is fine. I have reduce the size of the card paragraph because without reducing size I am unable to fix responsiveness....I think it looking fine .there is no problem now ..I have also fix the problem which was arises when clicking on Book Button

**Review by anmode — APPROVED** [review]
great!

**Pull request merged**
