### PR TITLE
Solved Issue #285 🚀 [Feature Request] - Make site to loader faster. [GSSoC'23]

### PR DESCRIPTION
**Pull request by vishnu9865**
## Related Issue
 - Convert all .jpg, .png files to .webp files
 - Find a way to make base64 images load faster.

Closes: #285 

## Description of Changes
 - Converted all .jpg and .png files to .webp.
 - All the dependencies were updated according to above changes.
 - Images with fixed width and height were converted into `<Image />` components for image optimization provided by NextJS 13 `next/image`.

#### Regarding loading Base64 Images faster.
 - I couldn't find a suitable solution to this problem as the root cause I think is the Base64 format itself ( can be termed as a accidental side effect).
 - Regarding this conclusion, I refer this article: https://bunny.net/blog/why-optimizing-your-images-with-base64-is-almost-always-a-bad-idea/
 - The article illustrates that the base64 format size for a moderate to large image exceeds the size of the image itself thus slowing down the server ( based on my understanding of the article ).
 - The only solution is to compress the image too much which doesn't seem like a good solution as it looses too much quality or resolution ( obviously becomes unusable).

## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [x] I have included comments in areas that may be difficult to understand.
- [x] I have made corresponding updates to the project documentation.
- [x] My changes have not introduced any new warnings.

@anmode Sir,
 - If there is any possible solutions or changes required in this PR. Please feel free to ask and am always happy to help 👍🏽.
 - Sorry, Couldn't create a PR sooner due to
    - Having semester in the middle of this.
    - I became obsessed with making base64 images load faster. 😅

Thanks in advance of taking your time for this PR.
Regards,
Jeyavishnu @vishnu9865

### CODE REVIEW

**Review by anmode — APPROVED** [review]
look good! but I would have 2 reviews.
just run `npx prettier --write .` to fix the test
@MohitGupta121 @Abhinavcode13  test it locally by using authentication please.

**Comment by vishnu9865** [comment]
@anmode ok sir working on it

**Comment by vishnu9865** [comment]
@anmode Sir,
I ran the command 👍🚀🚀
Thank you for your time.
https://github.com/anmode/grabtern-frontend/pull/317/commits/b2dd01644188f3c3adda61570997823117ccd9b5

**Comment by anmode** [comment]
> @anmode Sir, I ran the command 👍🚀🚀 Thank you for your time. [b2dd016](https://github.com/anmode/grabtern-frontend/commit/b2dd01644188f3c3adda61570997823117ccd9b5)

It's good! Will merge it soon. you can start working on another issue....

**Review by Illaf — APPROVED** [review]

**Comment by anmode** [comment]
Congrats @vishnu9865 on your first contribution

**Comment by vishnu9865** [comment]
@anmode Thank you sir, I hope to contribute more to this wonderful project. 🚀☺️☺️☺️👍

**Comment by vishnu9865** [comment]
@anmode Sir,
Can you kindly add `level` tags, that would be helpful for GSSoC'23.
Thank you for you time.
Regards,
Jeyavishnu @vishnu9865

**Comment by anmode** [comment]
@vishnu9865 Sorry to say! but there are error in this pR. I checked and tested. when I was develop branch and this comes when Your pR merged.

**Comment by anmode** [comment]
Please first of all fix it!

**Comment by vishnu9865** [comment]
Ok sir I will look into it.

**Comment by vishnu9865** [comment]
@anmode Sir Can you give any information on the Error like Screenshots or anything else.
Thank you

**Comment by anmode** [comment]
you were trying to use the Image component, but you haven't imported it from the appropriate library. If you are using Next.js, you should import the Image component from the next/image package. Also, you should use the new operator when creating an instance of the Image class.. No worries I fixed. it.

**Comment by anmode** [comment]
Please the issue I assigned need to complete asap! It would be great if you can start it over.

**Comment by vishnu9865** [comment]
> Please the issue I assigned need to complete asap! It would be great if you can start it over.

Yes sir, I made a commit to the branch fixing it just now 😅. Sorry for the inconvenience. And about the assigned issue I am designing it in figma right now. Will update you shortly. 🚀🚀🚀

**Comment by anmode** [comment]
> > Please the issue I assigned need to complete asap! It would be great if you can start it over.
> 
> Yes sir, I made a commit to the branch fixing it just now 😅. Sorry for the inconvenience. And about the assigned issue I am designing it in figma right now. Will update you shortly. 🚀🚀🚀

Cool, waiting to see new figma design

**Comment by vishnu9865** [comment]
@anmode Sir,
I made another mistake Sir, we had to `import Image from 'next/image'` in `[mentorUsername].page.js`
I am sorry for the inconvenience Sir.
Thank you for your time.
Regards,
@vishnu9865

**Pull request merged**
