### PR TITLE
revamp: list items design on homepage ✨

### PR DESCRIPTION
**Pull request by 0xabdulkhalid**
## Related Issue

Closes: #581 

## Description of Changes
- Revamped the design of the List and It's items on Homepage.
- Added tailwind utility classes to revamp the design properly.

## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [x] I have included comments in areas that may be difficult to understand.
- [x] I have made corresponding updates to the project documentation.
- [x] My changes have not introduced any new warnings.

## Screenshots

<table border="2">
        <tr>
            <th>O R I G I N A L </th>
            <th>U P D A T E D</th>
        </tr>
        <tr>
            <td>
                <table border="1">
                    <tr>
                        <th>MOBILE</th>
                        <th>DESKTOP</th>
                    </tr>
                    <tr>
                        <td>

Screen Shot 2023-07-23 at 08 00 50

</td>
                        <td>

Screenshot 2023-07-23 at 08-00-08 GrabTern Grab Your Internship

</td>
                    </tr>
                </table>
            </td>
            <td>
                <table border="1">
                    <tr>
                        <th>MOBILE</th>
                        <th>DESKTOP</th>
                    </tr>
                    <tr>
                        <td>

Screen Shot 2023-07-23 at 07 57 03

</td>
                        <td>

Screenshot 2023-07-23 at 07-51-24 GrabTern Grab Your Internship

</td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>

### CODE REVIEW

**Comment by 0xabdulkhalid** [comment]
Hey there @anmode, PR has been Opened!

You review is highly appreciated 🙌🏻

**Comment by anmode** [comment]
Two more fixes
1. Size of logo at nav bar should be increased and aligned properly 
2.  Please change the test to have any three good mentor at good positions
Screenshot 2023-07-23 at 5 14 54 PM

**Comment by 0xabdulkhalid** [comment]
@anmode i thought that this a design that left intentionally, Does this not ?

**Comment by anmode** [comment]
No no @0xabdulkhalid design is perfect please do not change it.

**Comment by 0xabdulkhalid** [comment]
If yes, then @anmode we can merge this PR now!

**Comment by 0xabdulkhalid** [comment]
I'm from South @anmode, i can't understand.

Please try to explain it in English.

**Comment by 0xabdulkhalid** [comment]
### Done @anmode !

Screenshot 2023-07-25 at 07-03-25 GrabTern Grab Your Internship

**Comment by 0xabdulkhalid** [comment]
Now this PR is ready to merge @anmode 🚀

**Comment by 0xabdulkhalid** [comment]
## Important Note 🚨
- I would like to bring this PR #513 for your consideration, because you haven't added `level` labels for that.
Please make sure to add them so that GSSoC Backend can count that contribution.

**Comment by Isha988** [comment]
@0xabdulkhalid  and @anmode the changes in `components/UI/Card/IconCard.js` are distorting testimonial, service and mentor section's card.

**Comment by 0xabdulkhalid** [comment]
@Isha988 Can you include any screenshots of distortion here to make necessary changes.

**Comment by Isha988** [comment]
> @Isha988 Can you include any screenshots of distortion here to make necessary changes.

@0xabdulkhalid please look at this
Screenshot_2023-07-25-13-59-46-47_40deb401b9ffe8e1df2f1cc5ba480b12
The quote icon was in left but now it comes in center

**Comment by 0xabdulkhalid** [comment]
Done @Isha988 👍🏻 

image

**Comment by 0xabdulkhalid** [comment]
> Now this PR is ready to merge @anmode rocket

# 📌 📝

**Review by anmode — APPROVED** [review]
Thanks @0xabdulkhalid

**Comment by anmode** [comment]
Thanks @Isha988 for reviewing!

**Pull request merged**
