### PR TITLE
Enhancing UI of Internship and Hackathon page

### PR DESCRIPTION
**Pull request by MAXASSASSINS**
## Enhancing UI of Internship and Hackathon page

Closes: #517 

## Description of Changes

- Set max width to 7xl
- Added responsive breakpoints
- Increased the roundness of labels

## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [x] I have included comments in areas that may be difficult to understand.
- [x] I have made corresponding updates to the project documentation.
- [x] My changes have not introduced any new warnings.

## Screenshots

|           Original           |           Updated           |
| :--------------------------: | :-------------------------: |
| screenshot-2023-07-15-17-37-20 | screenshot-2023-07-16-17-24-58 |
| screenshot-2023-07-15-18-36-57 | screenshot-2023-07-16-17-27-32 |

### CODE REVIEW

**Comment by anmode** [comment]
Could you also implement selecting multiple tags?  and then providing the search result and also add a column to add hackathon or suggest hackthon so anyone can suggest?

**Comment by anmode** [comment]
I'll make it as level 3

**Comment by MAXASSASSINS** [comment]
Sure I'll do that

**Comment by MAXASSASSINS** [comment]
Hey @anmode I have added the multiple filters functionality.

**Comment by MAXASSASSINS** [comment]
Hey @anmode, I am thinking about whether it is good for any random person who is visiting Grabtern to add hackathons and internship details. And if someone is adding wrong information that will be bad as well.
What are your thoughts?

**Comment by anmode** [comment]
> Hey @anmode, I am thinking about whether it is good for any random person who is visiting Grabtern to add hackathons and internship details. And if someone is adding wrong information that will be bad as well.
> What are your thoughts?

Yeah that's why, tha data will come to us and we will add it after verification.
One api for sending data from frontend to backend..
And other api for reflecting the data from backend to frontend that requires verification check.
No worries api I'll create or you can create a follow Up pR for that. So two level 3 pRs will complete this feature

**Comment by MAXASSASSINS** [comment]
Great I'll do both

**Comment by anmode** [comment]
@MAXASSASSINS So you can push the changes.. np I'll make this pR as WIP

**Comment by MAXASSASSINS** [comment]
Hey @anmode I have created the add internship component.

**Comment by anmode** [comment]
Cool, same form can be used at other places..
Like as now in hackathon section.

**Comment by anmode** [comment]
One thing...you create add internship page... make it as component so this form can be reused in other places..

I can better explain on meet...please dm me if you did not get my point

**Comment by MAXASSASSINS** [comment]
Are you talking about the modal taking full screen in mobile view?

**Comment by anmode** [comment]
> @anmode are you talking about the modal taking the full screen in mobile view?

haa whi.. i think thoda padding de do

**Comment by MAXASSASSINS** [comment]
Hey @anmode I have made the changes. Please have a look and let me know your thoughts.

Screenshot 2023-07-23 at 5 05 26 PM

**Comment by MAXASSASSINS** [comment]
@anmode I have made the changes. Your feedback will be appreciated.

**Review by anmode — APPROVED** [review]
Thanks for this!!

**Comment by anmode** [comment]
Next PR Idea could be adding hackthons....:)
I would really appriciate if you can make add internship to work for hackthon too!.
I mean a component a form type:
will pass prop to component... as state is intern-
intern pic , intern des., intern name and links and tags will show with accordingly..


mainly component can be used in any case if intern or hackthon or anyother thing.. Hope you get that.. :)

**Comment by MAXASSASSINS** [comment]
Sounds good,  should I create a new issue for that @anmode?

**Pull request merged**
