### PR TITLE
feat: Font color change

### PR DESCRIPTION
**Pull request by Vidip-Ghosh**
## Related Issue

Closes: #554 

## Description of Changes

Changed the font color of the headings or bold words of privacy page, refunds page.
Reduced padding of mobile devices.

For example:
- Added a new function to handle XYZ.
- Updated the ABC module to fix the bug.
- Refactored code in the DEF class for improved performance.
-->

## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [ ] I have conducted a self-review of my code.
- [ ] I have included comments in areas that may be difficult to understand.
- [x] I have made corresponding updates to the project documentation.
- [x] My changes have not introduced any new warnings.

## Screenshots

Please provide any necessary screenshots to illustrate the changes made.

### CODE REVIEW

**Comment by Vidip-Ghosh** [comment]
Screenshot 2023-07-23 at 16 39 28
Screenshot 2023-07-23 at 16 37 31
Screenshot 2023-07-23 at 16 31 41
Screenshot 2023-07-23 at 16 30 55

@anmode I hope now its alright. 
I reduced the margin and padding as well as increased max-width for Mobile devices.

**Comment by anmode** [comment]
Ab bhi same h vidip...in my phone kaafi padding aa rhi h

**Comment by Vidip-Ghosh** [comment]
image
image
@anmode please check.

**Comment by Vidip-Ghosh** [comment]
@anmode 
Please review the changes being made

**Comment by anmode** [comment]
Cool vidip thankss... last small fix which is hover effect in table of content to our theme!

**Comment by Vidip-Ghosh** [comment]
Done with the changes

**Comment by anmode** [comment]
vidip lastly yeh box haina... shadow effect isse remove krdo.. keep it simple

**Comment by Vidip-Ghosh** [comment]
> vidip lastly yeh box haina... shadow effect isse remove krdo.. keep it simple

I have removed the box. Please check

**Comment by Vidip-Ghosh** [comment]
@anmode If changes are alright, please merge this PR so that in other PR these changes might not get push.

**Pull request merged**
