### PR TITLE
Scroll to top button added (new PR)

### PR DESCRIPTION
**Pull request by kaashikaagrawal**
## Related Issue : No scroll to top button 

Added a scroll to top button that matches theme of the website.

Closes: #334 

## Description of Changes

- Added scrolltotop.js component
- Added ScrolltoTop css file
- added the component into the footer component so it appears on all pages that have a footer called.

## Checklist:

- [ x] My code adheres to the established style guidelines of this project.
- [ x] I have conducted a self-review of my code.
- [ x] I have included comments in areas that may be difficult to understand.
- [ x] I have made corresponding updates to the project documentation.
- [ x] My changes have not introduced any new warnings.

## Screenshots

|           Original           |           Updated           |
| :--------------------------: | :-------------------------: |
| 
Screenshot 2023-06-27 120106
 | image |

### CODE REVIEW

**Comment by kaashikaagrawal** [comment]
is this PR mergeable?

**Comment by anmode** [comment]
there is conflict

**Comment by kaashikaagrawal** [comment]
it is saying this.
image

**Comment by anmode** [comment]
> it is saying this. image

your github is not sync... ab toh kaafi conflicts aagye h
you can create a fresh pR

**Pull request closed without merging**
