### PR TITLE
Feat select color#555

### PR DESCRIPTION
**Pull request by Vidip-Ghosh**
## Related Issue

Closes: #555 

## Description of Changes
Text color and background color changes on select. 

## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [ ] I have conducted a self-review of my code.
- [ ] I have included comments in areas that may be difficult to understand.
- [x] I have made corresponding updates to the project documentation.
- [x] My changes have not introduced any new warnings.

## Screenshots

https://github.com/anmode/grabtern-frontend/assets/91741581/176f5f68-efc3-4a35-89b4-7977586eec6b

### CODE REVIEW

**Comment by anmode** [comment]
great vidip liked it!

**Comment by anmode** [comment]
isss chodkr sbko remove krdo vidip: 
commit a7f5f03611a86f146e843c9a39ba4c2c33facfeb

**Comment by Vidip-Ghosh** [comment]
@anmode ek baar check krna. Abhi fir se push kiya hai changes.

**Comment by anmode** [comment]
vidip nahi hue remove

**Comment by Vidip-Ghosh** [comment]
> vidip nahi hue remove :(

git rebase -i HEAD~n kiya tha dubara push krne se pehle. 
Ab dusra kya solution hai?

**Pull request closed without merging**
