### PR TITLE
Contact form validation checked before alert sent message issue#393 r…

### PR DESCRIPTION
**Pull request by Geeta259**
…esolved

#393

Closes: #393

## Checklist:

- [x ] My code adheres to the established style guidelines of this project.
- [ x] I have conducted a self-review of my code.
- [ ] I have included comments in areas that may be difficult to understand.
- [ x] I have made corresponding updates to the project documentation.
- [ x] My changes have not introduced any new warnings.
Screenshot (400)
Screenshot (401)
Screenshot (402)
Screenshot (403)
Screenshot (404)
Screenshot (405)

@anmode Please review it issue#393 resolved !!

### CODE REVIEW

**Review by anmode — CHANGES_REQUESTED** [review]
Nopes! without using state hook, can we use any validation library? and Please use toast alert box

**Comment by Geeta259** [comment]
@anmode  Can apply normal JS validation without state hook in this form ?

**Comment by anmode** [comment]
> @anmode  Can apply normal JS validation without state hook in this form ?

there are libraries..like veeValidate.
It will cover validation and all cases  you will not have to write regrex.

I request u too do the same..libraries are veeValidate or React also provides please check.
Your work would be get easy but no forget to use react toast for alert

**Comment by Geeta259** [comment]
> > @anmode  Can apply normal JS validation without state hook in this form ?
> 
> there are libraries..like veeValidate. It will cover validation and all cases you will not have to write regrex.
> 
> I request u too do the same..libraries are veeValidate or React also provides please check. Your work would be get easy but no forget to use react toast for alert

@anmode check #427
used react formik library to validate and toast alert to show error messages and confirmation alert!!

**Pull request closed without merging**
