### PR TITLE
added calendar page

### PR DESCRIPTION
**Pull request by Illaf**
## Related Issue

Closes: #[issue number]

## Checklist:

- [ ] My code adheres to the established style guidelines of this project.
- [ ] I have conducted a self-review of my code.
- [ ] I have included comments in areas that may be difficult to understand.
- [ ] I have made corresponding updates to the project documentation.
- [ ] My changes have not introduced any new warnings.

## Screenshots

|           Original           |           Updated           |
| :--------------------------: | :-------------------------: |
| Original screenshot | Updated screenshot |

Please provide any necessary screenshots to illustrate the changes made.

### CODE REVIEW

**Comment by anmode** [comment]
yeh complete ni hui n?? I think form m issue h validation ki... blank form pr bhi button click horha h

**Comment by Illaf** [comment]
> yeh complete ni hui n?? I think form m issue h validation ki... blank form pr bhi button click horha h

abhi complete nhi h

**Comment by anmode** [comment]
Oh shit, i Replied on incorrect pR actually login wali ke liye tha woh

**Comment by Illaf** [comment]
> > yeh complete ni hui n?? I think form m issue h validation ki... blank form pr bhi button click horha h
> 
> abhi complete nhi h

vhi m soch rhi thi validation kaha s aaya isme 💀😂

**Pull request closed without merging**
