### PR TITLE
Mentor Registration using Magic url

### PR DESCRIPTION
**Pull request by Isha988**
Created form to register mentor using magic url.

### CODE REVIEW

**Comment by anmode** [comment]
Screenshot 2023-08-28 at 8 07 05 AM
Please  fix this

**Comment by anmode** [comment]
All rest is good! Cool

**Comment by Isha988** [comment]
> Please fix this

Okay, will do it in evening.

**Comment by anmode** [comment]
> > Please fix this
> 
> Okay, will do it in evening.

haa sure no worries!..

**Pull request merged**
