### PR TITLE
updated hero section final

### PR DESCRIPTION
**Pull request by itsmohit097**
## Related Issue

Closes: #[#295]

## Description of Changes
update the hero section

## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [x] I have included comments in areas that may be difficult to understand.
- [x] I have made corresponding updates to the project documentation.
- [x] My changes have not introduced any new warnings.

## Screenshots

|           Original           |           Updated           |
| :--------------------------: | :-------------------------: |
| ![Original screenshot]
244480173-31b44f3a-7e75-451f-9254-bf6d751b9552

 | ![Updated screenshot] |   
Screenshot (106) 

Please provide any necessary screenshots to illustrate the changes made.

### CODE REVIEW

**Comment by anmode** [comment]
Mohit I appreciate,
1. Still not responsive
2. I think you could use tailwind to it's best as i see you write too much css. and media queries
3. Header section or I can top part of hero section link and button are not same as theme

**Comment by itsmohit097** [comment]
> Mohit I appreciate,
> 
> 1. Still not responsive
> 2. I think you could use tailwind to it's best as i see you write too much css. and media queries
> 3. Header section or I can top part of hero section link and button are not same as theme

1. yeah i am trying to make it fully responsive.
2. I tried to use tailwind but its not working so i use simple css.
3. you said i don't have to worry about navbar.

**Comment by ShreyaDhiman24** [comment]
> I wish to work on Navbar design @anmode .

**Comment by anmode** [comment]
> > Mohit I appreciate,
> > 
> > 1. Still not responsive
> > 2. I think you could use tailwind to it's best as i see you write too much css. and media queries
> > 3. Header section or I can top part of hero section link and button are not same as theme
> 
> 1. yeah i am trying to make it fully responsive.
> 2. I tried to use tailwind but its not working so i use simple css.
> 3. you said i don't have to worry about navbar.

No no,please see carefully that's not the nav..
Nav is different.
Hero section have above links nd button ig. Header section nd on scrolling nav comes

**Comment by anmode** [comment]
> > I wish to work on Navbar design @anmode . Can I raise another issue for that?

Oh sorry, actually there is a pR already.

**Comment by anmode** [comment]
@itsmohit097 please use tailwind classes, that's why i provided the code too

**Comment by anmode** [comment]
@itsmohit097 sorry! You were unable to complete it and really this is asap issue.. you know i waited for you to complete since a long..
Hope so  to get nice contribution from your side in future.. thanks

**Pull request closed without merging**
