### PR TITLE
new hero section

### PR DESCRIPTION
**Pull request by itsmohit097**
## Related Issue

Closes: #[#295]

## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [x] I have included comments in areas that may be difficult to understand.
- [x] I have made corresponding updates to the project documentation.
- [x] My changes have not introduced any new warnings.

## Screenshots

|           Original           |           Updated           |
| :--------------------------: | :-------------------------: |
| Original screenshot](https://github.com/anmode/grabtern-frontend/assets/125040386/e9132a78-0655-48e0-bc6c-8e3959190b9d)
| Updated screenshot](https://github.com/anmode/grabtern-frontend/assets/125040386/2e94167b-040e-4c97-a2ec-9833e02c1ee2) |

Please provide any necessary screenshots to illustrate the changes made.

### CODE REVIEW

**Comment by anmode** [comment]
1. Vector cut problem
2. Is it not optimized for mobile view
3. Hyperlink in hero section are not visible see the new theme

**Comment by itsmohit097** [comment]
i'll make the hyperlink not visible 
it is not responsive yet

**Comment by anmode** [comment]
you can choose any good vector from here: https://www.freepik.com/vectors/mentor

**Comment by itsmohit097** [comment]
vector cut problem solved
hyperlink problem solved
responsiveness is not done
check the new commit

**Comment by anmode** [comment]
Please remove the background of the image you used and please align it.. all the things are not perfectly aligned.. as you too notice..

**Comment by itsmohit097** [comment]
please do meet @anmode

**Comment by anmode** [comment]
ok tomorrow 9 am?

**Comment by anmode** [comment]
Hii, 10 am please...I'll send link here

**Comment by anmode** [comment]
@itsmohit097 https://meet.google.com/fvn-exwd-khj

**Comment by itsmohit097** [comment]
Sorry i was late.
Can we do it now?

**Comment by anmode** [comment]
> @anmode 
> Sorry i was busy with some other stuff.
> Can we do it now?

At 3? Dm me at 9368086395

**Comment by anmode** [comment]
> @anmode 
> Sorry i was busy with some other stuff.
> Can we do it now?

At 3? Dm me at 9368086395

**Comment by anmode** [comment]
available??

**Comment by itsmohit097** [comment]
> available??
I'm doing some changes and its working 
alignment and vector img problem will be solved 
responsiveness will be left only

**Comment by anmode** [comment]
Okk cool

**Comment by anmode** [comment]
You can use same tailwind classes as in theme ig it will solve responsiveness i advice not to use media queries. If there is no way.. you can go for queries

**Comment by anmode** [comment]
You can use same tailwind classes as in theme ig it will solve responsiveness i advice not to use media queries. If there is no way.. you can go for queries

**Comment by anmode** [comment]
@itsmohit097 ? any progress

**Comment by itsmohit097** [comment]
check this out 
i tried to solve all problem
@anmode

**Pull request closed without merging**
