### PR TITLE
Created LICENSE

### PR DESCRIPTION
**Pull request by S-ishita**
## Related Issue

Closes: #186 

## Description of Changes

added license
## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [x] I have included comments in areas that may be difficult to understand.
- [x] I have made corresponding updates to the project documentation.
- [x] My changes have not introduced any new warnings.

## Screenshots

|           Original           |           Updated           |
| :--------------------------: | :-------------------------: |
| ![Original screenshot]
Screenshot from 2023-05-30 19-44-14
 | ![Updated screenshot]
Screenshot from 2023-05-30 19-44-06
|

### CODE REVIEW

**Comment by anmode** [comment]
Is this license ok? I do not believe in AI-generated licenses.. Sometime they give wrong and when we are talking in context

**Comment by S-ishita** [comment]
Well all repos have same licenses.This is standard github license

**Comment by anmode** [comment]
You have to customize it! please check- https://choosealicense.com/licenses/ .

**Comment by anmode** [comment]
@S-ishita just change name to Anmol Agrawal. I think it would be good

**Comment by anmode** [comment]
merged! congrats

**Pull request merged**
