### PR TITLE
component extraction ( mentor registration form)

### PR DESCRIPTION
**Pull request by Isha988**
## Related Issue
follow up of PR #384 

## Description of Changes
1. Extracted day input and time zone input component from schedule step of mentor form
2. removed "tw-" prefix from classes

### CODE REVIEW

**Comment by anmode** [comment]
Isha you use `tw`....as other part in website is using. Actually a PR on footer optimization changed this config...

**Comment by Isha988** [comment]
> Isha can you use `tw`....as other part in website is using. Actually a PR on footer optimization changed this config. I updated
> 
> #403 see
> 
> for easy you can revert this commit in your PR: [56778be](https://github.com/anmode/grabtern-frontend/pull/402/commits/56778bef75e508fc96a7d3d819dfab3fddd9e5b0)

Done👍

**Comment by anmode** [comment]
Now form validation left! ig

**Comment by Isha988** [comment]
> Now form validation left! ig

Ya.

**Comment by anmode** [comment]
Let's merge this! and you can create another pR for form Validation.
1. We can divide in mentor form regisration in three pR
2. Your pR count will also increased.

Division is ok as this is nice issue!

**Pull request merged**
