### PR TITLE
Added grabtern email feature in ReadMe

### PR DESCRIPTION
**Pull request by coder12git**
I have added the documentation for grabtern email feature in ReadMe as stated in this issue -> #565.

### CODE REVIEW

**Comment by anmode** [comment]
We need to explain to the community that our email service is used in several places. The backend is concealed, but you can access emails using specific credentials. You can create an account, verify it, and also act as a mentor with verification. This way, contributors can experience the entire functionality by registering as both a mentor and a user. It would be great to provide a demo video to illustrate this. I will label it as `level 2.`

**Comment by coder12git** [comment]
> We need to explain to the community that our email service is used in several places. The backend is concealed, but you can access emails using specific credentials. You can create an account, verify it, and also act as a mentor with verification. This way, contributors can experience the entire functionality by registering as both a mentor and a user. It would be great to provide a demo video to illustrate this. I will label it as `level 2.`

Ok, you mean we need these things -
1. A brief description of this feature and how it is beneficial for contributors.
2. A demo video illustrating that
3. All credentials required

**Comment by anmode** [comment]
yess!

**Comment by coder12git** [comment]
> yess!

@anmode your email feature is not working, I tried multiple times to login with those credentials but it's saying login failed.
So, tell me how I could make a demo video now? Other than that I have done all the changes in readme

**Review by anmode — APPROVED** [review]
cool, bass vedio rh gyi h

**Comment by coder12git** [comment]
> cool, bass vedio rh gyi h

Done @anmode

**Pull request merged**
