### PR TITLE
Created Sidebar for Mentor Dashboard

### PR DESCRIPTION
**Pull request by coder12git**
I have created a sidebar for Mentor Dashboard as stated in issue no - #530.
Please review it!
grab

### CODE REVIEW

**Comment by anmode** [comment]
Good work, It is good to merge....
some styling changes needed:
1. Please could you try to incoporate our theme? background color to silver... I mean if you go to homepage you will find three colors mainly white , grey , purple....see tailwind config.

**Review by Illaf — COMMENTED** [review]
@coder12git   It looks good. You need to add hover effects to the options. Also there seems to be an unnecessary scroll in the sidebar.Try to use theme colors of the website.

**Comment by coder12git** [comment]
@anmode @Illaf I have done all changes, please review.
Screenshot 2023-07-21 192018

**Comment by anmode** [comment]
Thanks its good...congrats for your first pR..you can takeover more issues related to dashboard or can create issue too.

**Pull request merged**
