### PR TITLE
Feat: Making Grabtern A Progressive Web App ( PWA Support)

### PR DESCRIPTION
**Pull request by SubhamB2003**
## Related Issue

Closes: #648 

## Description of Changes

https://github.com/anmode/grabtern-frontend/assets/94003231/8b3fcc57-74a0-4f52-9979-8c95dfb43862

## Checklist:

- [ ] My code adheres to the established style guidelines of this project.
- [ ] I have conducted a self-review of my code.
- [ ] I have included comments in areas that may be difficult to understand.
- [ ] I have made corresponding updates to the project documentation.
- [ ] My changes have not introduced any new warnings.

## Screenshots

|           Original           |           Updated           |
| :--------------------------: | :-------------------------: |
| Original screenshot | Updated screenshot |

Please provide any necessary screenshots to illustrate the changes made.

### CODE REVIEW

**Comment by anmode** [comment]
Wow, bass yeh mobile m theek response de

**Comment by anmode** [comment]
@SubhamB2003 could you make this more optimized.
I think we can enhance it more. Let me dive in today into PWA.

By the really great work 👏

**Comment by anmode** [comment]
@SubhamB2003 could you make this more optimized.
I think we can enhance it more. Let me dive in today into PWA.

By the really great work 👏

**Comment by anmode** [comment]
@SubhamB2003 
Let me know if you are ready for this proposal.
This pR will grows longer. Will consider it as a mini project ( I'll provide letter too )
- Implementing PWA into Grabtern
1. Service worker
2. Https support
3. Offline managment.....
and many more to enhance the pWa

**Comment by SubhamB2003** [comment]
> @SubhamB2003 
> Let me know if you are ready for this proposal.
> This pR will grows longer. Will consider it as a mini project ( I'll provide letter too )
> - Implementing PWA into Grabtern
> 1. Service worker
> 2. Https support
> 3. Offline managment.....
> and many more to enhance the pWa

Yes. Currently I do not know many things about pwa I want to explore more so it should be a great learning process for me.

**Comment by anmode** [comment]
cool, then: https://www.youtube.com/watch?v=BByUknfLTuA&list=PLlrxD0HtieHjqO1pNqScMngrV7oFro-TY
Check out this!

**Comment by SubhamB2003** [comment]
Hey, @anmode I add the offline page can you check? 
And can you please also merge the pr actually I am really busy with other stuff.

**Comment by anmode** [comment]
I did not get the point? we already have these things in our public folder why again??

**Comment by SubhamB2003** [comment]
> I did not get the point? we already have these things in our public folder why again?? If you are busy with other things...so ok. Just keep your first commit up. I'll merge. Actually I was thinking to do PWA full in this PR.

Yes really sorry for that.
Actually, I update the fallback page that's why I say.
You can merge this pr it's updated.

**Comment by anmode** [comment]
That's ok but about this public folder? it contains so many files? which are same in main repo?? what is the significance

**Comment by SubhamB2003** [comment]
> That's ok but about this public folder? it contains so many files? which are same in main repo?? what is the significance you created public folder inside public folder why?? I think it is better to remove that

Ohh I am really sorry.

**Comment by SubhamB2003** [comment]
Updated. I removed the inner public folder now.

**Comment by anmode** [comment]
Just fix prettier, I'll merge then!.
But really I do not want to merge.. i was thinking to complete whole thing in this PR :(

**Comment by SubhamB2003** [comment]
> Just fix prettier, I'll merge then!. But really I do not want to merge.. i was thinking to complete whole thing in this PR :(

Yeah, I am really sorry for that. I added the basic things. 

And now also format the codebase.

**Comment by anmode** [comment]
chlo no worries thank for this!

**Pull request merged**
