### PR TITLE
Feat payment page

### PR DESCRIPTION
**Pull request by Vidip-Ghosh**
## Related Issue

Closes: #624 

## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [ ] I have conducted a self-review of my code.
- [ ] I have included comments in areas that may be difficult to understand.
- [x] I have made corresponding updates to the project documentation.
- [x] My changes have not introduced any new warnings.

## Screenshots
Screenshot 2023-08-06 at 17 48 36

### CODE REVIEW

**Comment by anmode** [comment]
Screenshot 2023-08-06 at 10 15 13 PM

Wow vidip a clean PR... Impressive.
Just make this page responsive and pR all set to be merged

**Comment by Vidip-Ghosh** [comment]
Screenshot 2023-08-06 at 22 37 27
Check this out @anmode

**Comment by Vidip-Ghosh** [comment]
@anmode Please review the changes. 
If changes are alright, please merge

**Comment by anmode** [comment]
uff conflicts aagye....baaki PR all set h

**Comment by Vidip-Ghosh** [comment]
> uff conflicts aagye....baaki PR all set h

I've resolved conflicts.

**Comment by Vidip-Ghosh** [comment]
> > Cool, mobile mode m UPI ID chip rhi h... Icon tab ke peeche
> 
> Okay, thik krta hu
I have made the changes. Please check

**Comment by Vidip-Ghosh** [comment]
> Cool, mobile mode m UPI ID chip rhi h... Icon tab ke peeche

Done with the changes

**Comment by anmode** [comment]
just pass this prettier,,
run on local
```
npx prettier --write .
```

do not forget that dot

**Comment by Vidip-Ghosh** [comment]
> just pass this prettier,, run on local
> 
> ```
> npx prettier --write .
> ```
> 
> do not forget that dot

Yes done

**Comment by anmode** [comment]
cool @Vidip-Ghosh

**Pull request merged**
