### PR TITLE
Enhanced Mentor cards

### PR DESCRIPTION
**Pull request by abhi03ruchi**
## Related Issue

Closes: #365 

## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [x] I have included comments in areas that may be difficult to understand.
- [x] I have made corresponding updates to the project documentation.
- [x] My changes have not introduced any new warnings.

## Screenshots

|           Original           |   
Screenshot 2023-06-21 at 1 36 06 AM

|        Updated           |
https://github.com/anmode/grabtern-frontend/assets/105661636/9974b4d4-8738-4b60-8776-dd927db999e6

) |

Please provide any necessary screenshots to illustrate the changes made.

### CODE REVIEW

**Comment by anmode** [comment]
Nice, A minor change...when we click share page the link do not copy. It just copied to clipboard.
but it should be copied.
Test by pasting

**Comment by anmode** [comment]
@abhi03ruchi can you create a follow up pR?? there is some issue with css see

**Comment by abhi03ruchi** [comment]
plz specify by sending a pic , I am unable to identify.

**Comment by anmode** [comment]
> plz send a pic, I am unable to identify.

just update your branch develop
1. sync your github repo
2. pull the latest changes
3. visit mentor page ( any mentor) you will css distorted

**Comment by anmode** [comment]
Screenshot 2023-06-21 at 11 17 11 AM

**Comment by anmode** [comment]
No worries! I found the fix

**Comment by abhi03ruchi** [comment]
ok

**Pull request merged**
