### PR TITLE
Work on page name, Meta Tag, SEO , Name In URL

### PR DESCRIPTION
**Pull request by itsmohit097**
## Related Issue [#284 ]

Closes: #[284]

## Description of Changes

- Favicon is changed and now it is more suited to site as i showed in the issue.
- Title is optimized to the relevant pages.

## Checklist:

- [ ] My code adheres to the established style guidelines of this project.
- [ ] I have conducted a self-review of my code.
- [ ] I have included comments in areas that may be difficult to understand.
- [ ] I have made corresponding updates to the project documentation.
- [ ] My changes have not introduced any new warnings.

## Screenshots

|           Original           |
Screenshot 2023-06-07 021339

|           Updated           |
Screenshot 2023-06-08 023019
mentors
contact us
And so on..

Pls add the label of level.

### CODE REVIEW

**Review by anmode — APPROVED** [review]
Cool Thanks @itsmohit097

**Comment by anmode** [comment]
Just fix the lint test:
`npx prettier --write`

**Comment by itsmohit097** [comment]
You can merge it now.

**Comment by itsmohit097** [comment]
@anmode please check

**Comment by itsmohit097** [comment]
I push the code again . Pls check it again it will work now.
@anmode

**Comment by anmode** [comment]
congrats @itsmohit097 your PR is merged

**Pull request merged**
