### PR TITLE
new hero section

### PR DESCRIPTION
**Pull request by itsmohit097**
## Related Issue   #295 
#295 
Convert the Hero section and you have to optimize for mobile view too

Closes: #[issue number]

## Description of Changes
- Change the theme of the hero section and for mobile view too.
- Also add some hovering effects to the nav menus
- **illustration yet to be added**
- **logo yet to be fixed**

## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [x] I have included comments in areas that may be difficult to understand.
- [ ] I have made corresponding updates to the project documentation.
- [x] My changes have not introduced any new warnings.

## Screenshots

|           Original           |       
244480173-31b44f3a-7e75-451f-9254-bf6d751b9552

|    Updated           |
Screenshot 2023-06-14 031018
Screenshot 2023-06-14 031134

### CODE REVIEW

**Comment by itsmohit097** [comment]
@anmode I made these changes till now i'll start working on it after 26th of june as i told you my end sem exams are going on now.

**Comment by anmode** [comment]
@itsmohit097 sorry do not continue this PR as of now. When you get free please ping me in this pR or on discord.

**Comment by anmode** [comment]
I have tagged `level 3`

**Comment by anmode** [comment]
One update you do not have take care of nav: https://github.com/anmode/grabtern-frontend/pull/372 . You focus on hero section.!!

**Comment by anmode** [comment]
@MohitGupta121 ?? So are you up for this! It is waiting please

**Comment by anmode** [comment]
@MohitGupta121 ?

**Comment by anmode** [comment]
That's cool, please try to complete asap many issues are depended on your pR.
Actually the things we really need the exact copy of the theme:
I provided you with the theme and also source code.

**Comment by anmode** [comment]
@itsmohit097 Just want to confirm are you working on this?? Actually this issue needs to addressed urgently!

**Comment by itsmohit097** [comment]
Yeah i'm working on it. I'll update u by tomorrow tomorrow evening.

**Comment by itsmohit097** [comment]
I forked the source code but it is not opening in my github desktop. I don't understand how to put the background image.
updated till now
Screenshot 2023-06-30 141610
when i add a demo background image with the same size before it happens like this.
I also use img tag  in the dashboard page but it also didn't work.
Screenshot 2023-06-30 141805

I have tried so many times but it didn't work.

**Comment by itsmohit097** [comment]
I forked the source code but it is not opening in my github desktop. I don't understand how to put the background image.
updated till now
Screenshot 2023-06-30 141610
when i add a demo background image with the same size before it happens like this.
I also use img tag  in the dashboard page but it also didn't work.
Screenshot 2023-06-30 141805

I have tried so many times but it didn't work.

**Comment by anmode** [comment]
availabe for meet?? 1 pm

**Comment by itsmohit097** [comment]
Yes 👍

**Comment by anmode** [comment]
email id please... i will schedule the meet

**Comment by itsmohit097** [comment]
mohitkumarece123@gmail.com

**Comment by anmode** [comment]
hey/

**Comment by itsmohit097** [comment]
wait i'm joining

**Comment by itsmohit097** [comment]
i joined it

**Comment by itsmohit097** [comment]
hello @anmode

**Comment by anmode** [comment]
you did not joined at time....i was waiting.. ok joining in 5 min please

**Comment by anmode** [comment]
@itsmohit097 any help needed?? or it is ok you are able to replicating?

**Comment by itsmohit097** [comment]
Everything is ok @anmode  
everything is done, only one thing is left it will be finally done by tomorrow morning till 10am.

**Comment by anmode** [comment]
that's cool! I will be waiting!

**Comment by itsmohit097** [comment]
ORIGINAL HERO SECTION

Screenshot (102)


UPDATED HERO SECTION

Screenshot (101)

illustrative image is not accessible so i use a demo image any further changes you want me to add or i can raise  a PR.

**Comment by anmode** [comment]
yeh mentors wala section cut kaise hogya? and bigger vector img  section we have to change.

**Comment by anmode** [comment]
raise PR.. Let's see

**Comment by anmode** [comment]
@itsmohit097 ?

**Comment by itsmohit097** [comment]
Raised a PR see here 
https://github.com/anmode/grabtern-frontend/pull/480#issue-1785559579

**Comment by itsmohit097** [comment]
> yeh mentors wala section cut kaise hogya? and bigger vector img section we have to change.

provided theme mei bhi same tha and bigger vector image access ni ho paa rha tha jo theme mila tha usse

**Comment by anmode** [comment]
Screenshot 2023-07-03 at 2 07 20 PM
i was talking about this?

**Comment by itsmohit097** [comment]
> Screenshot 2023-07-03 at 2 07 20 PM i was talking about this?
i'll correct it

**Pull request closed without merging**
