### PR TITLE
[Feature] Uniformity in UI of homepage

### PR DESCRIPTION
**Pull request by Isha988**
## Related Issue
Closes: #298 

There is pile up issue improve sections of homepge... This create a UI formity

## Description of Changes
Added background and changed the image of mentor section

### CODE REVIEW

**Comment by Isha988** [comment]
@anmode have a look at the changes, if you are okay with this so I will make rest of the changes.

**Comment by anmode** [comment]
It is good... it needs more improvement. I mean something it looks visually good.

**Comment by Isha988** [comment]
I will update you after I get some idea.

**Comment by Isha988** [comment]
Do we need such selection?

**Comment by anmode** [comment]
Nii, Acha So what we can do is I'll take some to think Home page.. Till time others are working on different parts of the Homepage. I'll merge this PR at last, You can do integration and can see for fixes in Uniformity (which may arise as different people on different sections..

We'll start creating Mentor Dashboard. 
the flow would be like...
1. Sidebar
2. Nav bar ( new one which is being developed)
3. Component based on sidebar ( profile, sessions, other section ( will update)).

I request you to create issue... so to increase issue count too,
1. side bar for mentor dashboard.
2. components ( one component one issue)

Then for user dashboard we will use same code but with some modification. backend I'll do. Mostly is created but I think i have to create some apis.


If you are up for this proposal. let me know. I'll pul hold on this pR.

**Comment by Isha988** [comment]
Okay, I am up for this proposal and will be creating new issues for mentor dashboard.

**Comment by anmode** [comment]
That would be cool! Thanks.

**Comment by anmode** [comment]
Isko update krdo! I'lll merge
Just merge with updated develop

**Comment by Isha988** [comment]
> Isko update krdo! I'lll merge Just merge with updated develop
> 
> For integration you can create a new PR when other homepage part will be merged

Screenshot_2023-06-21-12-36-13-22_40deb401b9ffe8e1df2f1cc5ba480b12
Is this section okay, if yes, then I will update this else will try to create something new

**Comment by anmode** [comment]
Ohh my bad how i forget! we would be removing this section as you created mentor page.... oh sorry

**Comment by Isha988** [comment]
In my opinion, we need this section as on our homepage we should have some action button/section which can navigate mentor to mentor page so that they can discover more about benefits and all the faqs.

**Comment by anmode** [comment]
> In my opinion, we need this section as on our homepage we should have some action button/section which can navigate mentor to mentor page so that they can discover more about benefits and all the faqs.

yeh bhi theek h but sbse upr button h `Be a Mentor` on which that page will open.....keeping section ok let's take views of others

@glokta1 @muhammadjufry @Illaf @Riyazul555

**Comment by Illaf** [comment]
@anmode I think it's not necessary as of now perks to be a mentor are not really justified.

**Comment by anmode** [comment]
abhi do pR pending h :(
idk i provided the new UI code too and this task is very simple..do not know why they are lacking...
I'll wait for one day... you can takeover issue of replicating new HOME Page... are you up for it??

**Comment by Isha988** [comment]
> abhi do pR pending h :( I'll wait for one day... you can takeover issue of replicating new HOME Page... are you up for it?? there is code of new Homepage Too!! The thing is copy code and made it working

Okay, then first I will work on replicating new homepage then on this PR.
Just mention that issue here.

**Comment by Isha988** [comment]
I am closing this as, its code become stale now and it also have some unnecessary changes.

**Comment by Isha988** [comment]
I am closing this as, its code become stale now and it also have some unnecessary changes.

**Pull request closed without merging**
