### PR TITLE
Added greet.yml

### PR DESCRIPTION
**Pull request by Abhinavcode13**
## Related Issue

Closes: #155 

## Description of Changes
Added greet bot

## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [x] I have included comments in areas that may be difficult to understand.
- [x] I have made corresponding updates to the project documentation.
- [x] My changes have not introduced any new warnings.

### CODE REVIEW

**Review by anmode — COMMENTED** [review]
already haina yeh toh?

**Comment by Abhinavcode13** [comment]
H kya @anmode thike me change karta hu fir

**Comment by anmode** [comment]
H...ismai n roles cases lga do.... I mean collaborator ko alag wish and 2nd-time contributor( I mean not a new contributor) differently

**Comment by anmode** [comment]
@Abhinavcode13

**Pull request closed without merging**
