### PR TITLE
feat: homepage for ``dashboard/mentor`` 

### PR DESCRIPTION
**Pull request by rishuraj1**
## Description of Changes

- add: new homepage which loads upon opening dashoard/mentor route.
- responsive to certain extents.
- made necessary changes to the sidebar too to show profile pic in place of icon.
- made different cards to show main information such as profile info, schedule, next session etc.

## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [x] I have included comments in areas that may be difficult to understand.
- [x] I have made corresponding updates to the project documentation.
- [x] My changes have not introduced any new warnings.

image

image

Since, there is no provision to check if mentor is logged in, I used @anmode to populate the page for now.
Also, I made this page assuming that the mentors after log in can only access the dashboard and not before login.

### CODE REVIEW

**Comment by anmode** [comment]
@rishuraj1 actually we have updated routing...could you please pull the latest changes into your branch nd update it.

**Comment by anmode** [comment]
Screenshot 2023-08-03 at 10 10 19 AM

I think green ki jagah agr white rkhe and then styling kre toh homepage cards ache lagenge...what's say?

**Comment by rishuraj1** [comment]
Nice idea, I will do that

**Comment by anmode** [comment]
@rishuraj1 just check this: we have updated routing technique.
https://github.com/anmode/grabtern-frontend/pull/656

**Comment by rishuraj1** [comment]
@anmode yup, did the necessary changes, please have a look

**Comment by anmode** [comment]
Cool, thanks.. some last improvment:
1. Mobile optimization
2. Clicking on again on notification bell did not close it.

**Comment by anmode** [comment]
Can you create a PR for mobile optimization for the dashboard?? To optimize other parts too??
I'm merging this for now!

**Comment by rishuraj1** [comment]
@anmode  alright works. thanks!

**Comment by anmode** [comment]
> @anmode alright works. thanks!

welcome and thank to you! for making this..

**Pull request merged**
