### PR TITLE
Fixing profile image upload on mentor form registration

### PR DESCRIPTION
**Pull request by MAXASSASSINS**
## Profile image upload on mentor form registration not working properly #342 

Closes: #342 

## Description of Changes
1. Adding accept property to the image tag to accept only images
2. Setting mentor profile image to an empty string if the currently selected file is undefined.

## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [x] I have included comments in areas that may be difficult to understand.
- [x] I have made corresponding updates to the project documentation.
- [x] My changes have not introduced any new warnings.

### Before resolving bug 1
https://github.com/anmode/grabtern-frontend/assets/97503316/c9ba6741-1cc4-4921-a667-a16613da1830

### After resolving bug 1
https://github.com/anmode/grabtern-frontend/assets/97503316/8cb413c3-3360-4de9-8389-cef0331a4610

### Before resolving bug 2
https://github.com/anmode/grabtern-frontend/assets/97503316/9bf79c51-1d2e-4f3a-b27b-2c5e5145d532

### After resolving bug 2
https://github.com/anmode/grabtern-frontend/assets/97503316/48d2a3bb-ae33-4e5c-b1e9-1ed77385c9ec

### CODE REVIEW

**Comment by anmode** [comment]
I was looking for this type: see- https://mentro.tech/mentor/apply
try to upload the image.. even LinkedIn has the same thing and other platform too

**Comment by MAXASSASSINS** [comment]
Hey @anmode the example you provided above is using a custom slider should I use MUI for the slider or create my slider component?

**Comment by anmode** [comment]
> Hey @anmode the example you provided above is using a custom slider should I use MUI for the slider or create my slider component?

if you can create component that would be cool and I this allow me to give level3 too

**Comment by MAXASSASSINS** [comment]
Hey @anmode sure I will create a new component but where will I add the CSS cause through tailwind you can't target the input slider thumb?

**Comment by anmode** [comment]
So then you create CSS file in styles folder..you can keep suitable file name of css file.

**Comment by MAXASSASSINS** [comment]
Hey @anmode I have made the image cropper component. Here is the video.

https://github.com/anmode/grabtern-frontend/assets/97503316/854b2be2-f076-4e85-a78a-60fd7283f83f

**Review by anmode — APPROVED** [review]
Cool, Thankss

**Pull request merged**
