### PR TITLE
Mentor form validation

### PR DESCRIPTION
**Pull request by Isha988**
## Related Issue

follow up for #384 

## Description of Changes
Added validation to mentor registration form

### CODE REVIEW

**Comment by Isha988** [comment]
Tell me your specific format for username so that I can add that in validation rules.

**Comment by anmode** [comment]
> Tell me your specific format for username so that I can add that in validation rules.

space should be avoided only! and no special symbol

**Comment by anmode** [comment]
Now this PR needs to be addressed!

**Comment by Isha988** [comment]
done👍

**Pull request merged**
