### PR TITLE
Solved #75 : Added Dropdown Card

### PR DESCRIPTION
**Pull request by crocmons**
Added Dropdown Card also fixing some css issue on mentor card #75 

[grabtern dropdown card.webm](https://github.com/anmode/grabtern-frontend/assets/106610322/ad21f427-f726-4027-87aa-7de23d5b83c1)

### CODE REVIEW

**Comment by anmode** [comment]
Screenshot 2023-06-02 at 9 52 58 AM
There is some issue please see!

**Review by anmode — CHANGES_REQUESTED** [review]
i must say the card is looking great. Very well done. but For scalability or long-term, this would not be good.
It would be a bit tricky...but can we have a card component?? that can be used anywhere. and that card component will have card.css too. so designing would also be easy...

**Comment by crocmons** [comment]
> Screenshot 2023-06-02 at 9 52 58 AM There is some issue please see!

@anmode  yeah, it should be great if I do this with reusable card component.. 
but in the dropdown there only one user & one mentor..how it appears 2 user?

Screenshot (380)

**Comment by anmode** [comment]
> @anmode yeah, it should be great if I do this with reusable card component.. but in the dropdown there only one user & one mentor..how it appears 2 users? Can you please check again ...is it still there?
> 
> Screenshot (380)

cool! yes it is still there.. could you please fetch the latest changes? just update you develop with upstream and merge to your branch

**Comment by crocmons** [comment]
updated the user in dropdown please check

**Review by anmode — APPROVED** [review]
Now it is okay and looks great. Thanks
1. Please make it a card component ( You have to deal with props. - if do not know I hope learning would be great)
2. Please make it responsive for mobile mode too.

**Comment by anmode** [comment]
@crocmons ? are you working?? any update

**Comment by crocmons** [comment]
> @crocmons ? are you working?? any update

well, I haven't started yet because I'm just little bit of a rush with my studies..... Give me some time I will do that...

**Review by crocmons — COMMENTED** [review]
updted code added dropdownCard

**Review by anmode — CHANGES_REQUESTED** [review]
I really like the changes. Let me check it on local. You did great changes and I have verify them I hope.

last change from you side - Improve the UI of card please

**Comment by crocmons** [comment]
@anmode updated the UI ...now the dropdown card is responsive for all devices.. please check & let me know is there any issue ..

**Comment by anmode** [comment]
@crocmons I just merge a PR of UI and logic fix with descent changes....please just update your PR and next your PR to be merged. As i planned

**Comment by anmode** [comment]
Please. I think card position and some logic changes are needed. reference pR:

**Comment by crocmons** [comment]
cool, I saw that I forgotten to remove the position in the dropdown card ..let me do this ...

**Comment by crocmons** [comment]
@anmode login url is not working please check..so that I can fix it on the user dropdown menu...

**Comment by anmode** [comment]
Ok! I fixed it. Three things.
1. Yes we are using Taliwind. if you wish you can use it.
2. We recently think of using `createContext` as a hook in React. see if you can use it. 
3. There is bit problem in UI just see..Test it pleaes, if any question please ping me

**Comment by crocmons** [comment]
one thing I also notice that the mentor card is blank ...why was that?
Screenshot (390)

**Comment by anmode** [comment]
> one thing I also notice that the mentor card is blank ...why was that? Screenshot (390)

Actually I moved the data.. it was production data. I created a dummy data. Request you to also create a dummy mentor data so development guys can use that.

**Comment by anmode** [comment]
@crocmons please could you complete it soon. actually there in need of a card. component.

**Comment by crocmons** [comment]
done please check now

**Comment by crocmons** [comment]
oops sorry display:inline style should be inside the img tag I included on the global.css file which is rewrite all the img display property .......yeah sure I will fix this ....

**Comment by anmode** [comment]
why this login button keeps sliding :)? please fix it

**Comment by crocmons** [comment]
> why this login button keeps sliding :)? please fix it

fix it check please

**Comment by anmode** [comment]
Thanks @crocmons.

**Pull request merged**
