### PR TITLE
Created Queries page for mentor dashboard

### PR DESCRIPTION
**Pull request by Priy002**
## Related Issue

Closes: #[issue number]

## Description of Changes
Created queries page for mentor dashboard. 
The first section has a heading of "Queries" and a subheading of "Pending ". This section contains a list of the pending queries. Each pending query is displayed in a div element with a heading of the query and a button that the mentor can click to answer the query.

The second section has a heading of "Answered ". This section contains a list of the answered queries. Each answered query is displayed in a div element with a heading of the query.

The third section is a form where the mentor can enter a new query. The form has an input field where the mentor can enter the query and a button that the mentor can click to submit the query.

## Checklist:

- [ ] My code adheres to the established style guidelines of this project.
- [ ] I have conducted a self-review of my code.
- [ ] I have included comments in areas that may be difficult to understand.
- [ ] I have made corresponding updates to the project documentation.
- [ ] My changes have not introduced any new warnings.

## Screenshots

|           Original           |           Updated           |
| :--------------------------: | :-------------------------: |
| Original screenshot | Updated screenshot |

Please provide any necessary screenshots to illustrate the changes made.

### CODE REVIEW

**Comment by Priy002** [comment]
I have created the Queries page as mentioned in issue #533 
Please review it 
Also I could not figure out how to see mentor dashboard and make changes locally; it will be needed for building UI of this page; Help me out there!

**Comment by anmode** [comment]
Please ping me on discord.. I will better explain on meet. and please look out this PR: https://github.com/anmode/grabtern-frontend/pull/564

Go to preview mode and visit: `/dashboard/mentor`

**Comment by anmode** [comment]
@Priy002 What's the update?

**Comment by Priy002** [comment]
> @Priy002 What's the update?

even after git pull
not able to see the updates
image
still getting this
image
what should I do?

**Comment by anmode** [comment]
Check your fork... it's not synced

**Comment by Priy002** [comment]
https://github.com/anmode/grabtern-frontend/assets/73902900/b34eee9c-8f86-428b-90e2-afb28868acc1

**Review by anmode — APPROVED** [review]
Cool, I liked the changes

**Comment by anmode** [comment]
last some fixes:
- Please see our UI got to prod version: www.grabtern.com ( our theme color)
- Reduce padding above queries heading

**Comment by Priy002** [comment]
> Cool, I liked the changes, Sorry for late review actuallly was very with production... see new site is live thanks to all of you!

no issues
site looks amazing!

**Comment by Priy002** [comment]
> last some fixes:
> 
> * Please see our UI got to prod version: [www.grabtern.com](http://www.grabtern.com) ( our theme color)
> * Reduce padding above queries heading
> * prettier fix run `npx prettier --write .`

checkout the PR

**Comment by anmode** [comment]
Hi, I checked... actually it is not funtional.. wait I got a idea:
Can we make it like Ticket?
I mean mentor can create ticket... and their query will come to use:

this page can be modify:
A simple for to create ticker:
1. Id ( will be randomly generated)
2. Description of that
3. You have to put a status flag ( if true that query will be in pending state if false then completed)

So api will carry this data to backend.. you just have to make it funtional and after fill form data should be created..

**Comment by Priy002** [comment]
> Hi, I checked... actually it is not funtional.. wait I got a idea: Can we make it like Ticket? `query -> create ticket` I mean mentor can create ticket... and their query will come to use:
> 
> this page can be modify: A simple form to create ticker:
> 
> 1. Id ( will be randomly generated)
> 2. Description of that
> 3. You have to put a status flag ( if true that query will be in pending state if false then completed)
> 
> * Please create a basic ticket form component so can be used at other place and import into ticket page
> 
> So api will carry this data to backend.. you just have to make it funtional and after fill form data should be created..

sounds good!
I'll try to work on this and will let you know!

**Comment by anmode** [comment]
@Priy002 any updates?

**Comment by Priy002** [comment]
> @Priy002 any updates?

implemented the functionality, need some clarification, i'll ping you on discord

**Comment by anmode** [comment]
@Priy002  any updates?

**Comment by Priy002** [comment]
https://github.com/anmode/grabtern-frontend/assets/73902900/e6bb3ea4-ecf6-4df3-b187-7c9373487c63

**Comment by anmode** [comment]
Liked your changes! Just resolve the conflicts and your pR is good to merge!

**Comment by anmode** [comment]
@Priy002 ok I fixed it... just need a little mobile responsiveness.

**Comment by anmode** [comment]
Let's do on next PR... Other parts needs improvment too!

**Comment by Priy002** [comment]
> Let's do on next PR... Other parts needs improvment too!

Sure!
besides mobile responsiveness which other parts needs improvements??

**Pull request merged**
