### PR TITLE
Enhancing the UI of login dropdown buttons #292

### PR DESCRIPTION
**Pull request by MAXASSASSINS**
## Enhancing the UI of login dropdown buttons #292

Closes: #292 

## Description of Changes

1. Removing previous CSS selectors and adding new ones to grab the buttons and adding separate border-radius to each of them.
3. To adjust the positioning of the login card, the top margin is increased.
4. Width of the buttons is changed to cover the whole line.

## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [x] I have included comments in areas that may be difficult to understand.
- [x] I have made corresponding updates to the project documentation.
- [x] My changes have not introduced any new warnings.

## Screenshots

|           Original           |
| :--------------------------: 

screenshot-2023-06-08-20-03-26

|           Updated           |
| :-------------------------: |

screenshot-2023-06-08-20-10-24

### CODE REVIEW

**Comment by anmode** [comment]
Screenshot 2023-06-09 at 8 06 04 AM
Position of card needs to be modified. Otherwise it look cool!

**Comment by anmode** [comment]
Screenshot 2023-06-09 at 8 06 59 AM
Css needs to be improved. Rounded corners

**Comment by MAXASSASSINS** [comment]
Sure I will do that.

**Comment by MAXASSASSINS** [comment]
Hey @anmode I have modified the login card's position and fixed the login button's roundness.

#### Before
244575598-421dace5-a3a9-411a-9e2e-eebf413426df


#### After
Screenshot 2023-06-09 at 12 14 40 PM

#### Login dropdown position before changes
244575466-307ba3df-89c6-4847-a68f-de49045e4796

#### Login dropdown after changes
Screenshot 2023-06-09 at 12 35 05 PM

**Comment by MohitGupta121** [comment]
@MAXASSASSINS can you please attach final recording of changes in PR description.

**Comment by anmode** [comment]
Screenshot 2023-06-09 at 12 49 28 PM
this! I was conveying

**Comment by MAXASSASSINS** [comment]
Hey, @MohitGupta121 I have updated the description of changes in the PR.
Let me know if you need any changes.
Thanks

**Review by MohitGupta121 — COMMENTED** [review]
@MAXASSASSINS LGTM, Thanks!

**Review by MohitGupta121 — APPROVED** [review]
Only small suggestion please add proper screen recording of your implementation it makes easy for reviewer.

**Comment by MohitGupta121** [comment]
@anmode PTAL, now it's need your review to before merge this PR.
Thankd.

**Comment by anmode** [comment]
> @anmode PTAL, now it's need your review to before merge this PR. Thankd.

Really thanks @MohitGupta121

**Comment by MAXASSASSINS** [comment]
Sure @anmode.

**Comment by anmode** [comment]
want to continue in this pR??

**Comment by MAXASSASSINS** [comment]
Yeah sure

**Comment by MAXASSASSINS** [comment]
Just let me know the details @anmode and we can start working on this

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
@MAXASSASSINS Please make changes as suggested in this [comment](https://github.com/anmode/grabtern-frontend/pull/302#pullrequestreview-1472394483) here in this PR if you want to take "Level 3"

**Comment by Abhinavcode13** [comment]
Let me know if any issue comes up @MohitGupta121 !

**Comment by MohitGupta121** [comment]
@Abhinavcode13 please choose any from [here](https://github.com/anmode/grabtern-frontend/issues?q=is%3Aissue+is%3Aopen+no%3Aassignee)

**Comment by MAXASSASSINS** [comment]
Hey @MohitGupta121 do you want me to create a new card component or make changes in the existing DropdownCard component

**Comment by MohitGupta121** [comment]
@MAXASSASSINS basically we need card component and then passing prop as link to that component. This way we can use card component anywhere.

So will you do that in this PR itself or another PR?
It's your choose.
If you choose this PR you get level-2 otherwise level-1

**Comment by MAXASSASSINS** [comment]
Okay, I will create a new component named Card. 
But I'm still not clear about this ` passing prop as link to that component`. 
Could you please help me with the above?
Thanks

**Comment by anmode** [comment]
> Okay, I will create a new component named Card. But I'm still not clear about this ` passing prop as link to that component`. Could you please help me with the above? Thanks @MohitGupta121

actually forget about that....just think a way to use card. First of create a card component. Then Will proceed ahead

**Review by Abhinavcode13 — APPROVED** [review]

**Comment by MAXASSASSINS** [comment]
Sure @anmode. Let me create the card component first then I'll ping you.

**Comment by MAXASSASSINS** [comment]
Hey, @anmode @MohitGupta121 is this something you guys are looking for?

Screenshot 2023-06-10 at 3 01 56 PM

**Review by MohitGupta121 — APPROVED** [review]

**Comment by anmode** [comment]
uff!! Drop down card... We want to use this drop-down card.
when you comes first time it sees login button ( when click this card should with option login as user or mentor) and when user logged in same card will have option logout or dashboard.....

**Comment by anmode** [comment]
As of ok! Ui is a good merging then. You can open a new issue for creating a login card. if wanna work.

**Pull request merged**
