### PR TITLE
feat:Font Color

### PR DESCRIPTION
**Pull request by Vidip-Ghosh**
## Related Issue

Closes: #554 

## Description of Changes
Changed the font color of the headings or bold words of privacy page, refunds page. 

## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [] I have conducted a self-review of my code.
- [] I have included comments in areas that may be difficult to understand.
- [x] I have made corresponding updates to the project documentation.
- [x] My changes have not introduced any new warnings.

## Screenshots

|           Original           |           Updated           |
| :--------------------------: | :-------------------------: |
| Original screenshot | Updated screenshot |
Screenshot 2023-07-21 at 11 34 34
Screenshot 2023-07-21 at 11 32 14

Please provide any necessary screenshots to illustrate the changes made.

### CODE REVIEW

**Comment by anmode** [comment]
color theek ni h vidip... clearly see color of sign up button whi h hamara color

**Comment by anmode** [comment]
> > color theek ni h vidip... clearly see color of sign up button whi h hamara color
> 
> So, font color should be same as sign up color button. Am I right?

haa ig whi code h..

**Comment by anmode** [comment]
update kro branch...yeh homepage pr doctor ki theme kaise aarhi h

**Comment by anmode** [comment]
Vidip one thing for future... please keep some good sounding branch name like `fix:privacyPolicy` and also PR title too...
this is not ok to keep fixisuee...

**Comment by Vidip-Ghosh** [comment]
> Vidip one thing for future... please keep some good sounding branch name like `fix:privacyPolicy` and also PR title too... this is not ok to keep fixisuee...

Yes sure I'll take care of the same

**Comment by Vidip-Ghosh** [comment]
Now check @anmode 
I've updated the branch

**Comment by anmode** [comment]
Haa.. I'm waiting:)

**Comment by Vidip-Ghosh** [comment]
@anmode Please check

**Comment by anmode** [comment]
Screenshot 2023-07-22 at 2 06 33 PM
unrelated changes into your PR

**Comment by Vidip-Ghosh** [comment]
> Screenshot 2023-07-22 at 2 06 33 PM unrelated changes into your PR

Previous commit remove krte time aaye ye changes. Vo remove bhi nhi hue.
Kaise solve kru?

**Pull request closed without merging**
