### PR TITLE
Added no. of commits and Contributor title and also all the commits can now be seen.

### PR DESCRIPTION
**Pull request by Sch476**
Closes issue : #698 

Video : 

https://github.com/anmode/grabtern-frontend/assets/127319225/c4b62582-7df9-4036-96ea-a48c547d5d32

## Checklist:

- [x ] My code adheres to the established style guidelines of this project.
- [ x] I have conducted a self-review of my code.
- [ x] I have included comments in areas that may be difficult to understand.
- [ ] I have made corresponding updates to the project documentation.
- [ ] My changes have not introduced any new warnings.

### CODE REVIEW

**Comment by anmode** [comment]
cool just last:
```
npx prettier --write 

to pass test

**Comment by anmode** [comment]
I provided level 3, as you really did hard work to fix the problem that is causing.. btw kya dikkat thi?

**Comment by Sch476** [comment]
Should I use the command ??

**Comment by Sch476** [comment]
Profile Card ko galti se modify kar diyta tha thoda aur logic me issue tha isliye 30 commits dikha raha tha

**Comment by anmode** [comment]
agla issue kch aisa ho skta , iska profile page bhi bn jaye wha aur futhure details aajaye...
like no. of pRs and link of all prs and profile page also have a export button so we can generate a pdf.. boht shi feature hoga yeh waise

**Comment by Sch476** [comment]
Like the one of GSSOC leaderboard ??

**Comment by anmode** [comment]
I haven't seen pr haa Link of PR bhi fetch krna h and thoda UI acha rkhna h profile page k and user can export it as pdf and pdf bhi achi defined ho!

**Comment by Sch476** [comment]
npx prettier --write . kar diya iss command ko run . Abb ??

**Comment by anmode** [comment]
Now push krdo new changes

**Comment by anmode** [comment]
Why? You closed it and deleted branxh too??

**Pull request closed without merging**
