### PR TITLE
Add Appropriate Page with Search Bar and Filters  to "View More Hackathons" Button and Update Hackathons Content

### PR DESCRIPTION
**Pull request by Nishitbaria**
## Related Issue
The "View More Hackathons" button in the hackathons section of the website currently reloads the page upon clicking, instead of navigating to a designated page or section displaying additional hackathons. This results in a poor user experience and does not provide users with the expected functionality to explore more hackathons. Additionally, the hackathons section needs to be updated with appropriate hackathon content to ensure accurate and up-to-date information.

Closes: [#353 ]
## Description of Changes
- Modified the route and created page  for the "View More Hackathons" button to redirect users to the designated page or section.
- The hackathons page contain search bar,filter and saving hackathon option
- Added new hackathon content to the hackathons section, ensuring accuracy and relevance.

## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [x] I have included comments in areas that may be difficult to understand.
- [x] I have made corresponding updates to the project documentation.
- [x] My changes have not introduced any new warnings.

## Screenshots

|           Original           |           Updated           |
| :--------------------------: | :-------------------------: |
| Original screenshot | Updated screenshot  WhatsApp Image 2023-06-21 at 15 12 04|

Please feel free to suggest changes

### CODE REVIEW

**Comment by Nishitbaria** [comment]
Please review and merge pr with appropriate level and tag

**Comment by anmode** [comment]
Again same thing!
Background not needed and it deforming the UI. Please this is not the way to do.
You should see UI see other parts of website you will get to know where you are lacking.

**Comment by Nishitbaria** [comment]
> Again same thing! Background not needed and it deforming the UI. Please this is not the way to do. You should see UI see other parts of website you will get to know where you are lacking.

Please tell me what you want clearly ?

**Comment by anmode** [comment]
build is failing

**Comment by Nishitbaria** [comment]
I deplyed my fork it is deployed 👍🏻[link]( https://grabtern-frontend-sigma.vercel.app/) please  check

**Comment by anmode** [comment]
Okay @Nishitbaria I do want your work to get wasted here is what you can do:
1. I see hackathon card on homepage their sizes are differing please fix that
2. As you create page: Just please same card there but a lot more ( if you can fetch hackthon details from any api if available that would be cool )

Try to have UI formity as i see you used colorful heading in hackathon page it is not good

**Comment by Nishitbaria** [comment]
Please review

**Comment by anmode** [comment]
Same:
1. When I go to hackathon page ( Card should same as they are in home page same design)
2. when i click on filter ( different UI - colorful links)
3. When click on bookmark a text `Remove` which in diff UI

The thing is UI is not Uniform.  please look into it.

**Comment by Nishitbaria** [comment]
> 

So lets clarify : 1. you dont want description of hackathons  on hacakthon page, you  want formal ui,you dont want tooltip on bookmark ? please confirm and explain clearly

**Comment by anmode** [comment]
My point is!
As we can show limited hackathons on the home page... but if the user wants to view more there should page where we have hackathon cards and we can pass data from the JSON file
The thing is to maintain the UI for the card as same shown on the home page.

**Comment by Nishitbaria** [comment]
> My point is! As we can show limited hackathons on the home page... but if the user wants to view more there should be a page where we have hackathon cards and we can pass data from the JSON file The thing is to maintain the UI for the card as same shown on the home page.

means you dont want description of hackathon on hackathon page

**Comment by anmode** [comment]
> > My point is! As we can show limited hackathons on the home page... but if the user wants to view more there should be a page where we have hackathon cards and we can pass data from the JSON file The thing is to maintain the UI for the card as same shown on the home page.
> 
> means you dont want description of hackathon on hackathon page

yess! we will link card to site

**Comment by Nishitbaria** [comment]
@anmode  I have made a new final pull request please review it #436

**Pull request closed without merging**
