### PR TITLE
Resolved Issue #266 enhance the section

### PR DESCRIPTION
**Pull request by abhi03ruchi**
## Related Issue

Closes: #266 

## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [x] I have included comments in areas that may be difficult to understand.
- [x] I have made corresponding updates to the project documentation.
- [x] My changes have not introduced any new warnings.

## Screenshots

|           Original      |
Screenshot 2023-06-17 at 12 03 12 PM | 
 |           Updated           |

Please provide any necessary screenshots to illustrate the changes made.

https://github.com/anmode/grabtern-frontend/assets/105661636/f8894236-d240-4750-9714-2766abee077c

### CODE REVIEW

**Comment by anmode** [comment]
Some fixes:
1. Screenshot 2023-06-17 at 2 54 20 PM
2.  Need optimization for mobile view...

**Review by anmode — CHANGES_REQUESTED** [review]
Please move all CSS for this component from global.css to a different file.
About.css in styles folder
then import it in about.js and use it.

New design is  nice!

**Comment by abhi03ruchi** [comment]
ok


> Please move all CSS for this component from global.css to a different file. About.css in styles folder then import it in about.js and use it.
> 
> New design is nice! Thanks @abhi03ruchi

**Comment by abhi03ruchi** [comment]
changes  made , plz review : 

https://github.com/anmode/grabtern-frontend/assets/105661636/6e57581f-c066-4a5c-a46e-8f09a25a4051

**Comment by anmode** [comment]
There is conflict! You can have to solve it.. and please @abhi03ruchi if place of that arrow can you use other vectors? it is not suiting though.
@Illaf ? any review

**Comment by abhi03ruchi** [comment]
I have created a new pr , with the changes made . plz, review and merge.

**Pull request closed without merging**
