### PR TITLE
Unused CSS file removal

### PR DESCRIPTION
**Pull request by Isha988**
## Related Issue
follow up for #508 

## Description of Changes

Working on removing unused CSS files.

### CODE REVIEW

**Comment by Isha988** [comment]
I am pushing small commit, just to get a range of deployment for every commit.

**Comment by Isha988** [comment]
I got this `components\basic\LoginDropdown.js` file today, I haven't noticed it yesterday. Do I replace that with this?

**Comment by Isha988** [comment]
Would you please tell me, why this [67b94b6](https://github.com/anmode/grabtern-frontend/pull/568/commits/67b94b61bc4e546daf5278e709c78f2dba14f52f) commit fail to deploy?

**Comment by Isha988** [comment]
I have removed the unused css files from style folder.
I don't know much about this folder ` public/assets/css`,  should I remove font Awesome, flaticon, bootstrap files because now we are using react icons and  tailwind .
Same with Slick and slicknav, as we are using owl carousel.

**Comment by anmode** [comment]
> Would you please tell me, why this [67b94b6](https://github.com/anmode/grabtern-frontend/pull/568/commits/67b94b61bc4e546daf5278e709c78f2dba14f52f) commit fail to deploy?

This was the reason:
```
./pages/hackathon.page.js
Module not found: Can't resolve '../styles/LoginDropdown.module.css'

https://nextjs.org/docs/messages/module-not-found

./pages/internship.page.js
Module not found: Can't resolve '../styles/LoginDropdown.module.css'

https://nextjs.org/docs/messages/module-not-found


> Build failed because of webpack errors
Error: Process completed with exit code 1.
```

**Comment by anmode** [comment]
> I have removed the unused css files from style folder. I don't know much about this folder ` public/assets/css`, should I remove font Awesome, flaticon, bootstrap files because now we are using react icons and tailwind . Same with Slick and slicknav, as we are using owl carousel.

yeah, you did correctly.

**Comment by anmode** [comment]
> I got this `components\basic\LoginDropdown.js` file today, I haven't noticed it yesterday. Do I replace that with this?

yeh whi h :)... haa hta dena isko bhi.. as you created new that was good..

**Comment by anmode** [comment]
uff! Conflicts aagye

**Review by muhammadjufry — APPROVED** [review]

**Comment by muhammadjufry** [comment]
Please resolve conflicts

**Comment by Isha988** [comment]
> Please resolve conflicts

done

**Comment by Isha988** [comment]
> should I remove font Awesome, flaticon, bootstrap files because now we are using react icons and tailwind .
> Same with Slick and slicknav, as we are using owl carousel.

any suggestions?

**Comment by anmode** [comment]
> 

oh sorry, I forgot to ans.. yes yes sure please remove it.

**Review by anmode — APPROVED** [review]
cool, let's do furthur in Next PR

**Pull request merged**
