### PR TITLE
feat: Sidebar improvements/new navbar for mobile devices

### PR DESCRIPTION
**Pull request by rishuraj1**
## Description of Changes
- fixed: sidebar
- add: on hover expand effect to the current sidebar for devices with width > 512px
- add: indicator for which page are you on
- add: navbar at bottom for devices with width <= 512px
- add: a menu for expanding more options in mobile devices.

## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [x] I have included comments in areas that may be difficult to understand.
- [x] I have made corresponding updates to the project documentation.
- [x] My changes have not introduced any new warnings.

## Screenshots

normal:
image

on Hover:
image

image

image

image

@anmode .

### CODE REVIEW

**Comment by anmode** [comment]
Wow Nice...
Last fix what i think will be good:
Change green to purple(our theme color)
Change hover text color( which you used of our theme color) to white

**Comment by rishuraj1** [comment]
@anmode  done with the changes.

**Comment by anmode** [comment]
Liked you changes!

**Comment by rishuraj1** [comment]
@anmode  how do i do that, can you plz guide.

**Comment by anmode** [comment]
No worries then I'll do.....you can start working on another issues...in the dashboard

**Pull request merged**
