### PR TITLE
epsa:Fixed issue #403

### PR DESCRIPTION
**Pull request by ePSA-eJya**
## Related Issue

Closes: #403 

## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [x] I have included comments in areas that may be difficult to understand.
- [x] I have made corresponding updates to the project documentation.
- [x] My changes have not introduced any new warnings.

## Screenshots

|           Original           |           Updated           |
| :--------------------------: | :-------------------------: |
| Original screenshot | 
image
 |

Please provide any necessary screenshots to illustrate the changes made.
 please merge the pr @anmode

### CODE REVIEW

**Comment by anmode** [comment]
@ePSA-eJya UI is not exact same :
1. Size is very large see.
2. Arraw hover effect and how it is behaving. 
check: https://grabtern-new-frontend.vercel.app/

**Comment by ePSA-eJya** [comment]
Yeah....I haven't fixed that yet....will do that today

**Comment by anmode** [comment]
> Yeah....I haven't fixed that yet....will do that today My files got lost....so I lost track

oh no!! np. take your time

**Comment by anmode** [comment]
Screenshot 2023-06-27 at 1 16 41 AM

UI of search bar can be improved ( rounded corner and bar is so large too. and make search icon as black)

one more thing it would be small change our new theme color is :

**Comment by ePSA-eJya** [comment]
@anmode

**Comment by anmode** [comment]
ok updated with develop! I hope build problem will be solved

**Comment by anmode** [comment]
https://github.com/anmode/grabtern-frontend/assets/88332977/b276e585-a2a9-4812-afcf-9e6c0831b163

There is container I think.. which is creating problem and distorting UI. 
see the new theme it is clean

**Comment by anmode** [comment]
@muhammadjufry could you review please

**Comment by anmode** [comment]
It is degrading UI see.. I can't accept. 
what you can do... copy whole testimonial code from repo i provided and make that work here!

**Comment by anmode** [comment]
@ePSA-eJya if you neeed we can have meet.. ping me on discord

**Comment by anmode** [comment]
@ePSA-eJya ?

**Comment by ePSA-eJya** [comment]
yes....i was busy last week .....have begun work.........will update in 2 days

**Comment by ePSA-eJya** [comment]
@anmode i think i wont be able to contine on this issue. its getting to complicated. 😞

**Pull request closed without merging**
