### PR TITLE
FInal Update

### PR DESCRIPTION
**Pull request by Nishitbaria**
## Related Issue
The "View More Hackathons" button in the hackathons section of the website currently reloads the page upon clicking, instead of navigating to a designated page or section displaying additional hackathons. This results in a poor user experience and does not provide users with the expected functionality to explore more hackathons. Additionally, the hackathons section needs to be updated with appropriate hackathon content to ensure accurate and up-to-date information.

Closes: #[#353]

## Description of Changes

- Modified the route and created page  for the "View More Hackathons" button to redirect users to the designated page or section.
- The hackathons page contain search bar,filter .
- Worked on your feedback 
- Added new hackathon content to the hackathons section, ensuring accuracy and relevance.
- Made size of all cards Same

## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [x] I have included comments in areas that may be difficult to understand.
- [x] I have made corresponding updates to the project documentation.
- [x] My changes have not introduced any new warnings.

## Screenshots

|           Original           |           Updated           |
| :--------------------------: | :-------------------------: |
|  Original screenshot| image image

Please provide any necessary screenshots to illustrate the changes made.

### CODE REVIEW

**Comment by anmode** [comment]
I really liked now @Nishitbaria you did great.. one question keeps me troubling.. I hope you can help 
We are using tailwind but if we use material UI... our bundle size would increase!

**Comment by Nishitbaria** [comment]
> I really liked now @Nishitbaria you did great.. one question keeps me troubling.. I hope you can help We are using tailwind but if we use material UI... our bundle size would increase!



> We are using tailwind but if we use material UI... our bundle size would increase!

We can use material UI,As it is helpful framework,we can manage bundle size by optimized build configuration and i have use Material UI's @material-ui/core/styles package, which provides a way to use individual components and styles without including the entire library. This can help you to cherry-pick only the necessary components and minimize the impact on your bundle size.Please merge pull request

**Comment by Riyazul555** [comment]
This hackathon page looks good to me as of now @anmode ......let's wait for others reviews @glokta1 @Illaf @sayyedarib @muhammadjufry

**Comment by anmode** [comment]
One weird thing: When i compiled home page, all things rendered but hackathon section on homepage took time.
Please optimize it.
use image in wepb and compresed!

**Comment by Nishitbaria** [comment]
@anmode  Please review my pull request,I have used webp images and remove unwanted images,Page is working good,please please merge my pull request i will be greatful to you

**Comment by anmode** [comment]
> @anmode  Please review my pull request,I have used webp images and remove unwanted images,Page is working good,please please merge my pull request i will be grateful to you

Surely..@Nishitbaria you really created nicely. Will surely merged and it should be merged..let me check this locally tomorrow please

**Comment by anmode** [comment]
@Nishitbaria mobile mode is not optimized i see. This would be last fix ig

**Comment by Nishitbaria** [comment]
What do you mean  by mobile mode is not optimized ,what you want me  to do?

**Comment by Riyazul555** [comment]
The page is not optimised for smaller screens like mobile...... please optimize it @Nishitbaria

**Comment by Nishitbaria** [comment]
Do yo want me make responseive or fast loading?

**Comment by anmode** [comment]
> Do yo want me make responseive or fast loading?

Both are not possible? as responsive it is obvious otherwise mobile mode distorted

**Comment by anmode** [comment]
> @anmode What do you mean by mobile mode is not optimized ,what you want me to do?

Optimize means responsive as should be good in desktop mode and mobile mode both!

**Comment by Nishitbaria** [comment]
@anmode  Please review my changes ,I have made it mobile responsive ,made changes according to you

**Review by anmode — APPROVED** [review]
We really need developer like you!
Congrats @Nishitbaria

**Comment by Nishitbaria** [comment]
Thanks we really need  maintainers like you @anmode

**Pull request merged**
