### PR TITLE
Adding loading state in dashboard

### PR DESCRIPTION
**Pull request by Isha988**
1. Added loading and error in dashboard page
2. Used these state in different component

### CODE REVIEW

**Comment by Isha988** [comment]
@amode @muhammadjufry  Is this approach okay? If we are good to go with this, then I will design the PreLoader.js component.

1. This will only show loading or error for fetch, only when page component (like profile, queries, etc) load.
2. PreLoader component will cover full screen, hence page component will be hidden.

**Comment by anmode** [comment]
Screenshot 2023-08-15 at 1 55 10 PM
and one more thing.. We use toastify for alert, error, or success.

**Comment by Isha988** [comment]
> Screenshot 2023-08-15 at 1 55 10 PM and one more thing.. We use toastify for alert, error, or success.

Ok, I am correcting it

**Comment by Isha988** [comment]
Looking like this, please let me know your views
image
image

**Comment by Isha988** [comment]
I also wanna add some graphics like 👇, if some can search for similar graphics it will be great
image

**Comment by Isha988** [comment]
will run prettier command at last

**Comment by Isha988** [comment]
@anmode there is a problem edit session, please check it out.

**Comment by Isha988** [comment]
@anmode please check it out now, let me know if any changes are required.

**Comment by anmode** [comment]
Wow, It looks good sorry for late response... was out of  a bit

**Comment by anmode** [comment]
> I also wanna add some graphics like 👇, if some can search for similar graphics it will be great image

Okayy! I will surf for them!.

**Comment by Isha988** [comment]
> oops yoo

I will add them in next pr

**Comment by Isha988** [comment]
> @anmode there is a problem in edit session, please check it out.

Please, check it out once

**Comment by anmode** [comment]
> > @anmode there is a problem in edit session, please check it out.
> 
> Please, check it out once

theek h!

**Pull request merged**
