### PR TITLE
favicon changed to new logo

### PR DESCRIPTION
**Pull request by ShreyaDhiman24**
## Related Issue
#507 

Closes: #507

## Description of Changes

image

## Checklist:

- [ ] My code adheres to the established style guidelines of this project.
- [ ] I have conducted a self-review of my code.
- [ ] I have included comments in areas that may be difficult to understand.
- [ ] I have made corresponding updates to the project documentation.
- [ ] My changes have not introduced any new warnings.
- [x] All of the above

### CODE REVIEW

**Comment by anmode** [comment]
Loader bhi update krdo...usmai bhi purana logo h

**Comment by anmode** [comment]
m soch rha the loader m bhi new logo kaisa rhega?? ek baar. new logo loader m update krke dekhna..how it is looking?

**Comment by ShreyaDhiman24** [comment]
> m soch rha the loader m bhi new logo kaisa rhega?? ek baar. new logo loader m update krke dekhna..how it is looking?

It will look good ig..

**Comment by anmode** [comment]
phir toh krdo... issi pR m

**Comment by ShreyaDhiman24** [comment]
> phir toh krdo... issi pR m

but wo shi se align ni aara h lemme show..

**Comment by ShreyaDhiman24** [comment]
> > phir toh krdo... issi pR m
> 
> but wo shi se align ni aara h lemme show..

image

**Comment by anmode** [comment]
@ShreyaDhiman24 conflictss

**Comment by ShreyaDhiman24** [comment]
> @ShreyaDhiman24 conflictss

solved..

**Pull request merged**
