### PR TITLE
Contact us improved

### PR DESCRIPTION
**Pull request by ShreyaDhiman24**
## Related Issue

Closes: #380 

## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [x] I have included comments in areas that may be difficult to understand.
- [x] I have made corresponding updates to the project documentation.
-[x]My changes have not introduced any new warnings.

## Screenshots

[Screencast from 25-06-23 02:31:43 AM IST.webm](https://github.com/anmode/grabtern-frontend/assets/98320971/28f90d65-26dc-4e40-9379-6b64f4d22405)

### CODE REVIEW

**Comment by anmode** [comment]
Cool! @ShreyaDhiman24 ....

**Comment by anmode** [comment]
new theme is this ( light theme) - https://grabtern-new-frontend.vercel.app/
could you design this based on this theme it would be very great!

Note: I give level on revisions too! :)

**Comment by ShreyaDhiman24** [comment]
> new theme is this ( light theme) - https://grabtern-new-frontend.vercel.app/ could you design this based on this theme it would be very great!
> 
> Note: I give level on revisions too! :)

Yeah sure

**Comment by anmode** [comment]
> > new theme is this ( light theme) - https://grabtern-new-frontend.vercel.app/ could you design this based on this theme it would be very great!
> > Note: I give level on revisions too! :)
> 
> Yeah sure. Should I raise another issue for that ?

continue in this please!

**Comment by ShreyaDhiman24** [comment]
> > > new theme is this ( light theme) - https://grabtern-new-frontend.vercel.app/ could you design this based on this theme it would be very great!
> > > Note: I give level on revisions too! :)
> > 
> > 
> > Yeah sure. Should I raise another issue for that ?
> 
> thanks, continue in this please!

One more thing I would like to ask ..do i have to discard these changes and make another one for the theme accordingly or the changes made are also required ?

**Comment by anmode** [comment]
> > > > new theme is this ( light theme) - https://grabtern-new-frontend.vercel.app/ could you design this based on this theme it would be very great!
> > > > Note: I give level on revisions too! :)
> > > 
> > > 
> > > Yeah sure. Should I raise another issue for that ?
> > 
> > thanks, continue in this please!
> 
> One more thing I would like to ask ..do i have to discard these changes and make another one for the theme accordingly or the changes made are also required ?

Yaa commits would be discarded...
Actually we have to move to new theme. 
This pR would be awarded as level 3
Thanks

**Comment by ShreyaDhiman24** [comment]
> > > > > new theme is this ( light theme) - https://grabtern-new-frontend.vercel.app/ could you design this based on this theme it would be very great!
> > > > > Note: I give level on revisions too! :)
> > > > 
> > > > 
> > > > Yeah sure. Should I raise another issue for that ?
> > > 
> > > 
> > > thanks, continue in this please!
> > 
> > 
> > One more thing I would like to ask ..do i have to discard these changes and make another one for the theme accordingly or the changes made are also required ?
> 
> Yaa commits would be discarded... Actually we have to move to new theme. This pR would be awarded as level 3 Thanks

[Screencast from 26-06-23 02:14:00 PM IST.webm](https://github.com/anmode/grabtern-frontend/assets/98320971/5258eeef-23e0-4be3-8195-fbb92ac25130)

**Comment by anmode** [comment]
No @ShreyaDhiman24 ... This UI is far different with our new UI.

**Comment by anmode** [comment]
have a look shreya! we can have meet.. I do not want any confusion let your code wasted: https://github.com/anmode/grabtern-frontend/issues/295

**Comment by ShreyaDhiman24** [comment]
> not want any confusion and let your code wasted: #295

okay

**Comment by anmode** [comment]
`#845ec2`

**Comment by ShreyaDhiman24** [comment]
[Screencast from 26-06-23 09:50:47 PM IST.webm](https://github.com/anmode/grabtern-frontend/assets/98320971/1a293008-430a-46e7-977b-4f6355594d58)

**Comment by anmode** [comment]
last bass align fix:
Screenshot 2023-06-27 at 1 12 13 AM

**Comment by ShreyaDhiman24** [comment]
image

[Screencast from 27-06-23 04:54:27 PM IST.webm](https://github.com/anmode/grabtern-frontend/assets/98320971/33c280ec-84e5-4025-a763-57a32906eaeb)

Done

**Comment by anmode** [comment]
1. In desktop mode still form is not in center
2. You used dark grey ( may be used search bar but please see lighter which is used in footer where text is written)
ig that class for that color is `tw-bg-slate-100`

**Comment by ShreyaDhiman24** [comment]
> 1. In desktop mode still form is not in center
> 2. You used dark grey ( may be used search bar but please see lighter which is used in footer where text is written)
>    ig that class for that color is `tw-bg-slate-100`

Check this out

**Comment by anmode** [comment]
yaa bg look great but see container is not properly centered in desktop mode...

**Comment by ShreyaDhiman24** [comment]
> yaa bg look great but see container is not properly centered in desktop mode...

can you send me the screenshot as in my desktop it is aligned properly.

**Comment by anmode** [comment]
1280 X 389... my scrren size but in this it is still not in center.
and lastly for passing Lint test.. try to run `npx prettier --write .`
it fix the formatting

**Comment by anmode** [comment]
Congrats @ShreyaDhiman24 !!

**Pull request merged**
