### PR TITLE
added spinner in register page and login page

### PR DESCRIPTION
**Pull request by Illaf**
## Related Issue

Closes: #[issue number]

## Checklist:

- [ ] My code adheres to the established style guidelines of this project.
- [ ] I have conducted a self-review of my code.
- [ ] I have included comments in areas that may be difficult to understand.
- [ ] I have made corresponding updates to the project documentation.
- [ ] My changes have not introduced any new warnings.

## Screenshots

|           Original           |           Updated           |
| :--------------------------: | :-------------------------: |
| Original screenshot | Updated screenshot |

Please provide any necessary screenshots to illustrate the changes made.

### CODE REVIEW

**Comment by anmode** [comment]
Registration case m kaam ni kr rha h... and one more thing
please could you use `buttonUI` component.. you can find in UI folder inside components folder
login and register button m yhi component use krlo

**Comment by Illaf** [comment]
@anmode it is working.Have a look

https://github.com/anmode/grabtern-frontend/assets/114517448/bd772701-fd40-4a0a-becc-0ef51b8417bc

**Comment by Illaf** [comment]
> Registration case m kaam ni kr rha h... and one more thing please could you use `buttonUI` component.. you can find in UI folder inside components folder login and register button m yhi component use krlo @Illaf

Done!

**Comment by anmode** [comment]
button k size chota hogya boht.. dono registration and login m @Illaf

**Comment by Illaf** [comment]
> button k size chota hogya boht.. dono registration and login m @Illaf and from now onward.. willl do like.. button should be replaced with loader at the time of loading ( to prevent multiple api call , as some people keep clicking it) this should be implement at more places too where loader is used

Okay

**Comment by anmode** [comment]
@Illaf isse complete krlo phir calender ki UI krlena..

**Comment by Illaf** [comment]
@anmode got stuck in some work. will complete it today

**Comment by Illaf** [comment]
@anmode Please check this pr!

**Comment by anmode** [comment]
oh conflcts aagye!

**Comment by Illaf** [comment]
@anmode resolved

**Comment by anmode** [comment]
Good, Please apply same in forgot password and other places where api call is there....
needs to loader to come jb tk fail ya success n ho!

**Pull request merged**
