### PR TITLE
[Feature Request] - Convert forgot pass page and reset password page into New theme 

### PR DESCRIPTION
**Pull request by coder12git**
## Related Issue

Issue - #566

## Description of Changes

Convert the forgot pass page into the new theme.

Screenshot 2023-07-25 160732

### CODE REVIEW

**Comment by coder12git** [comment]
I have also redesigned the reset password page.
Screenshot 2023-07-25 214608

@anmode This is my first pr for this issue - #566. I will create one more pr for functionality separately.

**Comment by anmode** [comment]
Screenshot 2023-07-26 at 8 21 45 AM


Some design improvement: 
1. Actually i see on login page our logo replaced by a vector , please revert that..
2. Contact us , button and loader are not aligned properly and hover on contact Us acha ni h...
3. you can use vector: https://www.freepik.com/free-vector/access-control-system-abstract-concept_12085707.htm#query=forgot%20password&position=11&from_view=search&track=ais ..in forgot password page.

Functionality toh hi nii.. I mean bass design improvement main H.
Reset password m new PR bna dena.

**Comment by anmode** [comment]
All looks good! :)

**Comment by anmode** [comment]
I see, reset passoword mai confirm password k option ni aarha, please add confirm password too. and with eye sign to see ... you find visibility component so just import

**Comment by coder12git** [comment]
> I see, reset passoword mai confirm password k option ni aarha, please add confirm password too. and with eye sign to see ... you find visibility component so just import.
> 
> and to pass prettier test just run- `npx prettier --write .`

Done @anmode

**Pull request merged**
